// Nzovu Schedule API v1
//
// This file defines scheduling structures for recurring message execution.
// Schedules enable cron-like and calendar-based task automation.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: proto/schedule/v1/schedule.proto

package schedule

import (
	v11 "github.com/adrien19/nzovu/api/common/v1"
	v1 "github.com/adrien19/nzovu/api/message/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// State represents the schedule lifecycle stage.
type Schedule_Metadata_State int32

const (
	Schedule_Metadata_SCHEDULED Schedule_Metadata_State = 0 // Active, posting messages per schedule
	Schedule_Metadata_CANCELED  Schedule_Metadata_State = 1 // Permanently stopped (terminal state)
	Schedule_Metadata_ERRORED   Schedule_Metadata_State = 2 // Failed execution (check state_message for cause)
	Schedule_Metadata_PAUSED    Schedule_Metadata_State = 3 // Temporarily disabled (can resume with ResumeSchedule)
)

// Enum value maps for Schedule_Metadata_State.
var (
	Schedule_Metadata_State_name = map[int32]string{
		0: "SCHEDULED",
		1: "CANCELED",
		2: "ERRORED",
		3: "PAUSED",
	}
	Schedule_Metadata_State_value = map[string]int32{
		"SCHEDULED": 0,
		"CANCELED":  1,
		"ERRORED":   2,
		"PAUSED":    3,
	}
)

func (x Schedule_Metadata_State) Enum() *Schedule_Metadata_State {
	p := new(Schedule_Metadata_State)
	*p = x
	return p
}

func (x Schedule_Metadata_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Schedule_Metadata_State) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_schedule_v1_schedule_proto_enumTypes[0].Descriptor()
}

func (Schedule_Metadata_State) Type() protoreflect.EnumType {
	return &file_proto_schedule_v1_schedule_proto_enumTypes[0]
}

func (x Schedule_Metadata_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Schedule_Metadata_State.Descriptor instead.
func (Schedule_Metadata_State) EnumDescriptor() ([]byte, []int) {
	return file_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{0, 0, 0}
}

// ScheduleType categorizes the primary scheduling pattern.
// Determines which rule types are applicable.
type CalendarSchedule_ScheduleType int32

const (
	CalendarSchedule_MONTHLY       CalendarSchedule_ScheduleType = 0 // Executes monthly (1st of month, last Friday, etc.)
	CalendarSchedule_WEEKLY        CalendarSchedule_ScheduleType = 1 // Executes weekly (every Monday, bi-weekly, etc.)
	CalendarSchedule_DAILY         CalendarSchedule_ScheduleType = 2 // Executes daily (every day, weekdays only, etc.)
	CalendarSchedule_YEARLY        CalendarSchedule_ScheduleType = 3 // Executes yearly (birthdays, anniversaries, annual reports)
	CalendarSchedule_BUSINESS_DAYS CalendarSchedule_ScheduleType = 4 // Executes on business days (respects holidays/weekends)
	CalendarSchedule_CUSTOM        CalendarSchedule_ScheduleType = 5 // Reserved for wire compatibility; not supported by the v2 server
)

// Enum value maps for CalendarSchedule_ScheduleType.
var (
	CalendarSchedule_ScheduleType_name = map[int32]string{
		0: "MONTHLY",
		1: "WEEKLY",
		2: "DAILY",
		3: "YEARLY",
		4: "BUSINESS_DAYS",
		5: "CUSTOM",
	}
	CalendarSchedule_ScheduleType_value = map[string]int32{
		"MONTHLY":       0,
		"WEEKLY":        1,
		"DAILY":         2,
		"YEARLY":        3,
		"BUSINESS_DAYS": 4,
		"CUSTOM":        5,
	}
)

func (x CalendarSchedule_ScheduleType) Enum() *CalendarSchedule_ScheduleType {
	p := new(CalendarSchedule_ScheduleType)
	*p = x
	return p
}

func (x CalendarSchedule_ScheduleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CalendarSchedule_ScheduleType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_schedule_v1_schedule_proto_enumTypes[1].Descriptor()
}

func (CalendarSchedule_ScheduleType) Type() protoreflect.EnumType {
	return &file_proto_schedule_v1_schedule_proto_enumTypes[1]
}

func (x CalendarSchedule_ScheduleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CalendarSchedule_ScheduleType.Descriptor instead.
func (CalendarSchedule_ScheduleType) EnumDescriptor() ([]byte, []int) {
	return file_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{2, 0}
}

// DayType determines how to select the day within a month.
type MonthlyRule_DayType int32

const (
	MonthlyRule_DAY_OF_MONTH     MonthlyRule_DayType = 0 // Specific date (1-31)
	MonthlyRule_WEEKDAY_OF_MONTH MonthlyRule_DayType = 1 // Nth occurrence of weekday (first Monday, third Friday)
	MonthlyRule_LAST_WEEKDAY     MonthlyRule_DayType = 2 // Last occurrence of weekday (last Friday)
	MonthlyRule_LAST_DAY         MonthlyRule_DayType = 3 // Last day of month (handles varying month lengths)
)

// Enum value maps for MonthlyRule_DayType.
var (
	MonthlyRule_DayType_name = map[int32]string{
		0: "DAY_OF_MONTH",
		1: "WEEKDAY_OF_MONTH",
		2: "LAST_WEEKDAY",
		3: "LAST_DAY",
	}
	MonthlyRule_DayType_value = map[string]int32{
		"DAY_OF_MONTH":     0,
		"WEEKDAY_OF_MONTH": 1,
		"LAST_WEEKDAY":     2,
		"LAST_DAY":         3,
	}
)

func (x MonthlyRule_DayType) Enum() *MonthlyRule_DayType {
	p := new(MonthlyRule_DayType)
	*p = x
	return p
}

func (x MonthlyRule_DayType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MonthlyRule_DayType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_schedule_v1_schedule_proto_enumTypes[2].Descriptor()
}

func (MonthlyRule_DayType) Type() protoreflect.EnumType {
	return &file_proto_schedule_v1_schedule_proto_enumTypes[2]
}

func (x MonthlyRule_DayType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MonthlyRule_DayType.Descriptor instead.
func (MonthlyRule_DayType) EnumDescriptor() ([]byte, []int) {
	return file_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{4, 0}
}

// ExceptionType determines how to modify the schedule.
type CalendarException_ExceptionType int32

const (
	CalendarException_SKIP       CalendarException_ExceptionType = 0 // Don't execute on this date
	CalendarException_RESCHEDULE CalendarException_ExceptionType = 1 // Move execution to a different date
	CalendarException_EXTRA      CalendarException_ExceptionType = 2 // Add additional execution(s) on this date
)

// Enum value maps for CalendarException_ExceptionType.
var (
	CalendarException_ExceptionType_name = map[int32]string{
		0: "SKIP",
		1: "RESCHEDULE",
		2: "EXTRA",
	}
	CalendarException_ExceptionType_value = map[string]int32{
		"SKIP":       0,
		"RESCHEDULE": 1,
		"EXTRA":      2,
	}
)

func (x CalendarException_ExceptionType) Enum() *CalendarException_ExceptionType {
	p := new(CalendarException_ExceptionType)
	*p = x
	return p
}

func (x CalendarException_ExceptionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CalendarException_ExceptionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_schedule_v1_schedule_proto_enumTypes[3].Descriptor()
}

func (CalendarException_ExceptionType) Type() protoreflect.EnumType {
	return &file_proto_schedule_v1_schedule_proto_enumTypes[3]
}

func (x CalendarException_ExceptionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CalendarException_ExceptionType.Descriptor instead.
func (CalendarException_ExceptionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{17, 0}
}

// Schedule represents a recurring message posting pattern.
//
// Use schedules to:
// - Execute tasks at regular intervals (every hour, daily, weekly)
// - Implement business calendar logic (weekdays, holidays, month-end)
// - Create complex scheduling rules (first Monday of month, quarterly reports)
// - Automate maintenance tasks, reports, notifications, batch jobs
//
// Two scheduling modes:
// 1. Cron-based (legacy): Traditional Unix cron expressions
// 2. Calendar-based (recommended): Rich business calendar support
//
// Example - Daily report at 9 AM weekdays:
//
//	schedule := &schedule.Schedule{
//	    ScheduleId: "daily-sales-report",
//	    Metadata: &schedule.Schedule_Metadata{
//	        Payload: reportPayload,
//	        QueueName: "report-generator",
//	        CalendarSchedule: &schedule.CalendarSchedule{
//	            Type: schedule.CalendarSchedule_BUSINESS_DAYS,
//	            Rules: []*schedule.CalendarRule{{
//	                BusinessDays: &schedule.BusinessDaysRule{...},
//	                ExecutionTimes: []*schedule.TimeOfDay{{Hour: 9}},
//	            }},
//	            Timezone: "America/New_York",
//	        },
//	        Priority: 4,
//	        MaxMessages: 1000,  // Safety limit
//	    },
//	}
//
// Lifecycle:
// - SCHEDULED: Active, posting messages according to schedule
// - PAUSED: Temporarily disabled (can resume later)
// - CANCELED: Permanently stopped
// - ERRORED: Failed to execute (check state_message for details)
type Schedule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// schedule_id: Unique identifier for this schedule.
	// Must be unique across all schedules in your Nzovu instance.
	// Used for updating, pausing, resuming, or deleting the schedule.
	// Recommended format: descriptive-name or {system}-{task}-{frequency}
	ScheduleId string `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	// metadata: Schedule configuration and execution state.
	Metadata      *Schedule_Metadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schedule) Reset() {
	*x = Schedule{}
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schedule) ProtoMessage() {}

func (x *Schedule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schedule.ProtoReflect.Descriptor instead.
func (*Schedule) Descriptor() ([]byte, []int) {
	return file_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{0}
}

func (x *Schedule) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *Schedule) GetMetadata() *Schedule_Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ScheduleHistory captures execution history and state for a schedule.
// Used by GetScheduleHistory API to show past executions and timing.
type ScheduleHistory struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// messages: Messages created by this schedule.
	// Limited to recent history (e.g., last 100 executions).
	Messages []*v1.Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	// schedule_id: The schedule this history belongs to.
	ScheduleId string `protobuf:"bytes,2,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	// next_run: When the schedule will execute next.
	NextRun *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=next_run,json=nextRun,proto3" json:"next_run,omitempty"`
	// last_run: When the schedule last executed.
	LastRun *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_run,json=lastRun,proto3" json:"last_run,omitempty"`
	// created_at: When this schedule was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// updated_at: When this schedule was last modified.
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// executions: Durable schedule execution records. Unlike messages, these
	// records remain available after message retention or schedule deletion.
	Executions    []*ScheduleHistory_Execution `protobuf:"bytes,7,rep,name=executions,proto3" json:"executions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleHistory) Reset() {
	*x = ScheduleHistory{}
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleHistory) ProtoMessage() {}

func (x *ScheduleHistory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleHistory.ProtoReflect.Descriptor instead.
func (*ScheduleHistory) Descriptor() ([]byte, []int) {
	return file_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{1}
}

func (x *ScheduleHistory) GetMessages() []*v1.Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ScheduleHistory) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *ScheduleHistory) GetNextRun() *timestamppb.Timestamp {
	if x != nil {
		return x.NextRun
	}
	return nil
}

func (x *ScheduleHistory) GetLastRun() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRun
	}
	return nil
}

func (x *ScheduleHistory) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ScheduleHistory) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ScheduleHistory) GetExecutions() []*ScheduleHistory_Execution {
	if x != nil {
		return x.Executions
	}
	return nil
}

// CalendarSchedule defines rich business calendar-based scheduling.
//
// Supports complex scheduling patterns:
// - Business days only (skip weekends and holidays)
// - Relative dates (first Monday of month, last Friday)
// - Custom calendars per region/country
// - Exception handling (skip/reschedule specific dates)
// - Multiple execution times per day
//
// Example - Monthly reports on first business day at 8 AM and 5 PM:
//
//	calendar := &schedule.CalendarSchedule{
//	    Type: schedule.CalendarSchedule_BUSINESS_DAYS,
//	    Rules: []*schedule.CalendarRule{{
//	        BusinessDays: &schedule.BusinessDaysRule{
//	            BusinessCalendarId: "us-holidays",
//	        },
//	        ExecutionTimes: []*schedule.TimeOfDay{
//	            {Hour: 8, Minute: 0},
//	            {Hour: 17, Minute: 0},
//	        },
//	    }},
//	    Timezone: "America/New_York",
//	    BusinessCalendar: usHolidaysCalendar,
//	}
//
// Example - Quarterly board meeting (last Friday of Mar/Jun/Sep/Dec at 2 PM):
//
//	calendar := &schedule.CalendarSchedule{
//	    Type: schedule.CalendarSchedule_MONTHLY,
//	    Rules: []*schedule.CalendarRule{{
//	        Monthly: &schedule.MonthlyRule{
//	            DayType: schedule.MonthlyRule_LAST_WEEKDAY,
//	            DayValue: 5,  // Friday
//	            Months: []int32{3, 6, 9, 12},  // Q1, Q2, Q3, Q4
//	        },
//	        ExecutionTimes: []*schedule.TimeOfDay{{Hour: 14}},
//	    }},
//	    Timezone: "America/Los_Angeles",
//	}
type CalendarSchedule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type: Primary scheduling pattern.
	// Constrains which rule types can be used in rules field.
	Type CalendarSchedule_ScheduleType `protobuf:"varint,1,opt,name=type,proto3,enum=nzovu.api.schedule.v1.CalendarSchedule_ScheduleType" json:"type,omitempty"`
	// rules: Specific scheduling rules (when to execute).
	// Multiple rules = union of all matching times.
	// Example: Two rules for "weekdays at 9 AM" and "weekdays at 5 PM"
	Rules []*CalendarRule `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	// timezone: Canonical IANA timezone for all calendar schedule calculations.
	// Examples: "America/New_York", "Europe/London", "Asia/Tokyo"
	// Affects DST transitions, date boundaries, execution times.
	// Required for calendar schedules.
	Timezone string `protobuf:"bytes,3,opt,name=timezone,proto3" json:"timezone,omitempty"`
	// business_calendar: Holiday and weekend definitions.
	// Used by BUSINESS_DAYS schedules to skip non-working days.
	// Can include country-specific holidays, custom company holidays.
	BusinessCalendar *BusinessCalendar `protobuf:"bytes,4,opt,name=business_calendar,json=businessCalendar,proto3" json:"business_calendar,omitempty"`
	// exceptions: Override schedule for specific dates.
	// Use cases:
	// - Skip execution during maintenance windows
	// - Reschedule monthly report when month-end is holiday
	// - Add extra execution for one-time events
	Exceptions    []*CalendarException `protobuf:"bytes,5,rep,name=exceptions,proto3" json:"exceptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalendarSchedule) Reset() {
	*x = CalendarSchedule{}
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalendarSchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalendarSchedule) ProtoMessage() {}

func (x *CalendarSchedule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalendarSchedule.ProtoReflect.Descriptor instead.
func (*CalendarSchedule) Descriptor() ([]byte, []int) {
	return file_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{2}
}

func (x *CalendarSchedule) GetType() CalendarSchedule_ScheduleType {
	if x != nil {
		return x.Type
	}
	return CalendarSchedule_MONTHLY
}

func (x *CalendarSchedule) GetRules() []*CalendarRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *CalendarSchedule) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *CalendarSchedule) GetBusinessCalendar() *BusinessCalendar {
	if x != nil {
		return x.BusinessCalendar
	}
	return nil
}

func (x *CalendarSchedule) GetExceptions() []*CalendarException {
	if x != nil {
		return x.Exceptions
	}
	return nil
}

// CalendarRule defines a specific scheduling pattern within a CalendarSchedule.
// Each rule specifies WHEN (date pattern) and WHAT TIME (execution_times) to run.
//
// Example - Every Monday and Wednesday at 9 AM:
//
//	rule := &schedule.CalendarRule{
//	    Rule: &schedule.CalendarRule_Weekly{
//	        Weekly: &schedule.WeeklyRule{
//	            DaysOfWeek: []int32{1, 3},  // Monday, Wednesday
//	        },
//	    },
//	    ExecutionTimes: []*schedule.TimeOfDay{{Hour: 9}},
//	}
//
// Example - First day of every quarter at midnight:
//
//	rule := &schedule.CalendarRule{
//	    Rule: &schedule.CalendarRule_Monthly{
//	        Monthly: &schedule.MonthlyRule{
//	            DayType: schedule.MonthlyRule_DAY_OF_MONTH,
//	            DayValue: 1,
//	            Months: []int32{1, 4, 7, 10},  // Jan, Apr, Jul, Oct
//	        },
//	    },
//	    ExecutionTimes: []*schedule.TimeOfDay{{Hour: 0}},
//	}
type CalendarRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// rule: Date pattern determining which days to execute.
	// Choose one based on CalendarSchedule.type.
	//
	// Types that are valid to be assigned to Rule:
	//
	//	*CalendarRule_Monthly
	//	*CalendarRule_Weekly
	//	*CalendarRule_Daily
	//	*CalendarRule_Yearly
	//	*CalendarRule_BusinessDays
	//	*CalendarRule_Custom
	Rule isCalendarRule_Rule `protobuf_oneof:"rule"`
	// execution_times: What time(s) of day to execute on matching dates.
	// Multiple times = multiple executions per day.
	// Examples:
	//
	//	[{hour:9}] = once at 9 AM
	//	[{hour:8}, {hour:12}, {hour:17}] = three times daily
	//
	// If empty, defaults to midnight (00:00:00).
	ExecutionTimes []*TimeOfDay `protobuf:"bytes,7,rep,name=execution_times,json=executionTimes,proto3" json:"execution_times,omitempty"`
	// valid_from: Start date for this rule (inclusive).
	// Rule only applies on or after this date.
	// Use for seasonal schedules or phased rollouts.
	ValidFrom *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	// valid_until: End date for this rule (inclusive).
	// Rule only applies on or before this date.
	// Use for limited-time campaigns or temporary schedules.
	ValidUntil    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=valid_until,json=validUntil,proto3" json:"valid_until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalendarRule) Reset() {
	*x = CalendarRule{}
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalendarRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalendarRule) ProtoMessage() {}

func (x *CalendarRule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalendarRule.ProtoReflect.Descriptor instead.
func (*CalendarRule) Descriptor() ([]byte, []int) {
	return file_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{3}
}

func (x *CalendarRule) GetRule() isCalendarRule_Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

func (x *CalendarRule) GetMonthly() *MonthlyRule {
	if x != nil {
		if x, ok := x.Rule.(*CalendarRule_Monthly); ok {
			return x.Monthly
		}
	}
	return nil
}

func (x *CalendarRule) GetWeekly() *WeeklyRule {
	if x != nil {
		if x, ok := x.Rule.(*CalendarRule_Weekly); ok {
			return x.Weekly
		}
	}
	return nil
}

func (x *CalendarRule) GetDaily() *DailyRule {
	if x != nil {
		if x, ok := x.Rule.(*CalendarRule_Daily); ok {
			return x.Daily
		}
	}
	return nil
}

func (x *CalendarRule) GetYearly() *YearlyRule {
	if x != nil {
		if x, ok := x.Rule.(*CalendarRule_Yearly); ok {
			return x.Yearly
		}
	}
	return nil
}

func (x *CalendarRule) GetBusinessDays() *BusinessDaysRule {
	if x != nil {
		if x, ok := x.Rule.(*CalendarRule_BusinessDays); ok {
			return x.BusinessDays
		}
	}
	return nil
}

func (x *CalendarRule) GetCustom() *CustomRule {
	if x != nil {
		if x, ok := x.Rule.(*CalendarRule_Custom); ok {
			return x.Custom
		}
	}
	return nil
}

func (x *CalendarRule) GetExecutionTimes() []*TimeOfDay {
	if x != nil {
		return x.ExecutionTimes
	}
	return nil
}

func (x *CalendarRule) GetValidFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidFrom
	}
	return nil
}

func (x *CalendarRule) GetValidUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidUntil
	}
	return nil
}

type isCalendarRule_Rule interface {
	isCalendarRule_Rule()
}

type CalendarRule_Monthly struct {
	Monthly *MonthlyRule `protobuf:"bytes,1,opt,name=monthly,proto3,oneof"` // For MONTHLY schedules
}

type CalendarRule_Weekly struct {
	Weekly *WeeklyRule `protobuf:"bytes,2,opt,name=weekly,proto3,oneof"` // For WEEKLY schedules
}

type CalendarRule_Daily struct {
	Daily *DailyRule `protobuf:"bytes,3,opt,name=daily,proto3,oneof"` // For DAILY schedules
}

type CalendarRule_Yearly struct {
	Yearly *YearlyRule `protobuf:"bytes,4,opt,name=yearly,proto3,oneof"` // For YEARLY schedules
}

type CalendarRule_BusinessDays struct {
	BusinessDays *BusinessDaysRule `protobuf:"bytes,5,opt,name=business_days,json=businessDays,proto3,oneof"` // For BUSINESS_DAYS schedules
}

type CalendarRule_Custom struct {
	Custom *CustomRule `protobuf:"bytes,6,opt,name=custom,proto3,oneof"` // Reserved for wire compatibility; not supported by the v2 server
}

func (*CalendarRule_Monthly) isCalendarRule_Rule() {}

func (*CalendarRule_Weekly) isCalendarRule_Rule() {}

func (*CalendarRule_Daily) isCalendarRule_Rule() {}

func (*CalendarRule_Yearly) isCalendarRule_Rule() {}

func (*CalendarRule_BusinessDays) isCalendarRule_Rule() {}

func (*CalendarRule_Custom) isCalendarRule_Rule() {}

// MonthlyRule schedules execution on specific days of the month.
//
// Examples:
//
//	15th of every month:
//	  {day_type: DAY_OF_MONTH, day_value: 15}
//
//	First Monday of every month:
//	  {day_type: WEEKDAY_OF_MONTH, day_value: 1, occurrence: 1}
//
//	Last Friday of every month:
//	  {day_type: LAST_WEEKDAY, day_value: 5}
//
//	Last day of every month:
//	  {day_type: LAST_DAY}
//
//	15th of March, June, September, December:
//	  {day_type: DAY_OF_MONTH, day_value: 15, months: [3,6,9,12]}
type MonthlyRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// day_type: How to interpret day_value.
	DayType MonthlyRule_DayType `protobuf:"varint,1,opt,name=day_type,json=dayType,proto3,enum=nzovu.api.schedule.v1.MonthlyRule_DayType" json:"day_type,omitempty"`
	// day_value: Day number or weekday.
	// For DAY_OF_MONTH: 1-31 (values > month length skip that month)
	// For WEEKDAY_OF_MONTH/LAST_WEEKDAY: 1=Monday through 7=Sunday (ISO 8601)
	// For LAST_DAY: ignored
	DayValue int32 `protobuf:"varint,2,opt,name=day_value,json=dayValue,proto3" json:"day_value,omitempty"`
	// occurrence: Which occurrence of the weekday (for WEEKDAY_OF_MONTH).
	// 1 = first occurrence, 2 = second, 3 = third, 4 = fourth
	// 5 = fifth (rare, skips months without 5 occurrences)
	// -1 = last occurrence (equivalent to LAST_WEEKDAY)
	Occurrence int32 `protobuf:"varint,3,opt,name=occurrence,proto3" json:"occurrence,omitempty"`
	// months: Which months to apply this rule (1=January, 12=December).
	// Empty = all months.
	// Common patterns:
	//
	//	[3,6,9,12] = quarterly
	//	[1,4,7,10] = quarterly (different quarters)
	//	[1,7] = semi-annual
	Months        []int32 `protobuf:"varint,4,rep,packed,name=months,proto3" json:"months,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonthlyRule) Reset() {
	*x = MonthlyRule{}
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthlyRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlyRule) ProtoMessage() {}

func (x *MonthlyRule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlyRule.ProtoReflect.Descriptor instead.
func (*MonthlyRule) Descriptor() ([]byte, []int) {
	return file_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{4}
}

func (x *MonthlyRule) GetDayType() MonthlyRule_DayType {
	if x != nil {
		return x.DayType
	}
	return MonthlyRule_DAY_OF_MONTH
}

func (x *MonthlyRule) GetDayValue() int32 {
	if x != nil {
		return x.DayValue
	}
	return 0
}

func (x *MonthlyRule) GetOccurrence() int32 {
	if x != nil {
		return x.Occurrence
	}
	return 0
}

func (x *MonthlyRule) GetMonths() []int32 {
	if x != nil {
		return x.Months
	}
	return nil
}

// WeeklyRule schedules execution on specific days of the week.
//
// Examples:
//
//	Every Monday and Friday:
//	  {days_of_week: [1, 5]}
//
//	Every weekday (Mon-Fri):
//	  {days_of_week: [1, 2, 3, 4, 5]}
//
//	Every other week on Wednesday:
//	  {days_of_week: [3], week_interval: 2, start_week: "2024-01-03"}
type WeeklyRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// days_of_week: Which days of the week to execute.
	// ISO 8601 format: 1=Monday, 2=Tuesday, ..., 7=Sunday
	// Empty = all days (equivalent to daily schedule)
	DaysOfWeek []int32 `protobuf:"varint,1,rep,packed,name=days_of_week,json=daysOfWeek,proto3" json:"days_of_week,omitempty"`
	// week_interval: Execute every Nth week.
	// 1 = every week, 2 = every other week (bi-weekly), 4 = monthly (every 4 weeks)
	// Default: 1
	WeekInterval int32 `protobuf:"varint,2,opt,name=week_interval,json=weekInterval,proto3" json:"week_interval,omitempty"`
	// start_week: Reference date for week_interval calculation.
	// Week interval counts from this date's week.
	// Example: bi-weekly schedule starting Jan 1, 2024 executes on weeks of Jan 1, Jan 15, Jan 29, etc.
	// If not set, uses schedule creation date.
	StartWeek     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_week,json=startWeek,proto3" json:"start_week,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeeklyRule) Reset() {
	*x = WeeklyRule{}
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeeklyRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeeklyRule) ProtoMessage() {}

func (x *WeeklyRule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeeklyRule.ProtoReflect.Descriptor instead.
func (*WeeklyRule) Descriptor() ([]byte, []int) {
	return file_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{5}
}

func (x *WeeklyRule) GetDaysOfWeek() []int32 {
	if x != nil {
		return x.DaysOfWeek
	}
	return nil
}

func (x *WeeklyRule) GetWeekInterval() int32 {
	if x != nil {
		return x.WeekInterval
	}
	return 0
}

func (x *WeeklyRule) GetStartWeek() *timestamppb.Timestamp {
	if x != nil {
		return x.StartWeek
	}
	return nil
}

// DailyRule schedules execution every N days.
//
// Examples:
//
//	Every day:
//	  {day_interval: 1}
//
//	Every other day:
//	  {day_interval: 2}
//
//	Weekdays only:
//	  {day_interval: 1, weekdays_only: true}
//
//	Every 3 days starting from specific date:
//	  {day_interval: 3, start_date: "2024-01-01"}
type DailyRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// day_interval: Execute every Nth day.
	// 1 = every day, 2 = every other day, 7 = weekly
	// Default: 1
	DayInterval int32 `protobuf:"varint,1,opt,name=day_interval,json=dayInterval,proto3" json:"day_interval,omitempty"`
	// weekdays_only: If true, skip weekends (Saturday and Sunday).
	// Applies after day_interval calculation.
	// Example: {day_interval: 1, weekdays_only: true} = every weekday
	WeekdaysOnly bool `protobuf:"varint,2,opt,name=weekdays_only,json=weekdaysOnly,proto3" json:"weekdays_only,omitempty"`
	// start_date: Reference date for day_interval calculation.
	// Day interval counts from this date.
	// If not set, uses schedule creation date.
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyRule) Reset() {
	*x = DailyRule{}
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyRule) ProtoMessage() {}

func (x *DailyRule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyRule.ProtoReflect.Descriptor instead.
func (*DailyRule) Descriptor() ([]byte, []int) {
	return file_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{6}
}

func (x *DailyRule) GetDayInterval() int32 {
	if x != nil {
		return x.DayInterval
	}
	return 0
}

func (x *DailyRule) GetWeekdaysOnly() bool {
	if x != nil {
		return x.WeekdaysOnly
	}
	return false
}

func (x *DailyRule) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

// YearlyRule schedules execution once per year on a specific date.
//
// Examples:
//
//	January 1st (New Year's Day):
//	  {month: 1, day: 1}
//
//	December 25th (Christmas):
//	  {month: 12, day: 25}
//
//	February 29th (handles non-leap years):
//	  {month: 2, day: 29, adjust_for_leap_year: true}
type YearlyRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// month: Month of the year (1=January, 12=December).
	Month int32 `protobuf:"varint,1,opt,name=month,proto3" json:"month,omitempty"`
	// day: Day of the month (1-31).
	// Must be valid for the specified month.
	Day int32 `protobuf:"varint,2,opt,name=day,proto3" json:"day,omitempty"`
	// adjust_for_leap_year: How to handle Feb 29 on non-leap years.
	// If true: executes on Feb 28 on non-leap years
	// If false: skips execution on non-leap years
	AdjustForLeapYear bool `protobuf:"varint,3,opt,name=adjust_for_leap_year,json=adjustForLeapYear,proto3" json:"adjust_for_leap_year,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *YearlyRule) Reset() {
	*x = YearlyRule{}
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YearlyRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YearlyRule) ProtoMessage() {}

func (x *YearlyRule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YearlyRule.ProtoReflect.Descriptor instead.
func (*YearlyRule) Descriptor() ([]byte, []int) {
	return file_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{7}
}

func (x *YearlyRule) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *YearlyRule) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *YearlyRule) GetAdjustForLeapYear() bool {
	if x != nil {
		return x.AdjustForLeapYear
	}
	return false
}

// BusinessDaysRule schedules execution on business days (non-holidays, non-weekends).
//
// Examples:
//
//	Every business day:
//	  {business_calendar_id: "us-holidays"}
//
//	Day before each business day (for overnight processing):
//	  {business_calendar_id: "us-holidays", day_offset: -1}
//
//	Day after each business day:
//	  {business_calendar_id: "us-holidays", day_offset: 1}
type BusinessDaysRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// business_calendar_id: Reference to BusinessCalendar defining holidays/weekends.
	// Must match a calendar_id in CalendarSchedule.business_calendar.
	BusinessCalendarId string `protobuf:"bytes,1,opt,name=business_calendar_id,json=businessCalendarId,proto3" json:"business_calendar_id,omitempty"`
	// day_offset: Offset from business day.
	// 0 = on business day
	// -1 = day before business day (useful for overnight prep jobs)
	// 1 = day after business day
	// Note: Offset day might land on non-business day; schedule skips those.
	DayOffset     int32 `protobuf:"varint,2,opt,name=day_offset,json=dayOffset,proto3" json:"day_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BusinessDaysRule) Reset() {
	*x = BusinessDaysRule{}
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BusinessDaysRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessDaysRule) ProtoMessage() {}

func (x *BusinessDaysRule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessDaysRule.ProtoReflect.Descriptor instead.
func (*BusinessDaysRule) Descriptor() ([]byte, []int) {
	return file_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{8}
}

func (x *BusinessDaysRule) GetBusinessCalendarId() string {
	if x != nil {
		return x.BusinessCalendarId
	}
	return ""
}

func (x *BusinessDaysRule) GetDayOffset() int32 {
	if x != nil {
		return x.DayOffset
	}
	return 0
}

// CustomRule is reserved for wire compatibility.
// The v2 server rejects custom expression rules because it has no custom-rule processors.
type CustomRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// expression: Reserved custom scheduling expression.
	Expression string `protobuf:"bytes,1,opt,name=expression,proto3" json:"expression,omitempty"`
	// rule_type: Reserved custom rule processor identifier.
	RuleType string `protobuf:"bytes,2,opt,name=rule_type,json=ruleType,proto3" json:"rule_type,omitempty"`
	// parameters: Reserved custom rule parameters.
	Parameters    map[string]string `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomRule) Reset() {
	*x = CustomRule{}
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomRule) ProtoMessage() {}

func (x *CustomRule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomRule.ProtoReflect.Descriptor instead.
func (*CustomRule) Descriptor() ([]byte, []int) {
	return file_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{9}
}

func (x *CustomRule) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *CustomRule) GetRuleType() string {
	if x != nil {
		return x.RuleType
	}
	return ""
}

func (x *CustomRule) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// TimeOfDay specifies a time within a day (wall clock time).
//
// Examples:
//
//	9 AM: {hour: 9}
//	2:30 PM: {hour: 14, minute: 30}
//	Midnight: {hour: 0}
//	11:59:59 PM: {hour: 23, minute: 59, second: 59}
type TimeOfDay struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// hour: Hour of day (0-23), 24-hour format.
	Hour int32 `protobuf:"varint,1,opt,name=hour,proto3" json:"hour,omitempty"`
	// minute: Minute of hour (0-59). Default: 0
	Minute int32 `protobuf:"varint,2,opt,name=minute,proto3" json:"minute,omitempty"`
	// second: Second of minute (0-59). Default: 0
	// Most schedules don't need second precision.
	Second        int32 `protobuf:"varint,3,opt,name=second,proto3" json:"second,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeOfDay) Reset() {
	*x = TimeOfDay{}
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeOfDay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeOfDay) ProtoMessage() {}

func (x *TimeOfDay) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeOfDay.ProtoReflect.Descriptor instead.
func (*TimeOfDay) Descriptor() ([]byte, []int) {
	return file_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{10}
}

func (x *TimeOfDay) GetHour() int32 {
	if x != nil {
		return x.Hour
	}
	return 0
}

func (x *TimeOfDay) GetMinute() int32 {
	if x != nil {
		return x.Minute
	}
	return 0
}

func (x *TimeOfDay) GetSecond() int32 {
	if x != nil {
		return x.Second
	}
	return 0
}

// BusinessCalendar defines holidays and weekends for a region/organization.
// Used by BusinessDaysRule to determine working vs non-working days.
//
// Example - US federal holidays:
//
//	calendar := &schedule.BusinessCalendar{
//	    CalendarId: "us-federal",
//	    Name: "US Federal Holidays",
//	    Holidays: []*schedule.Holiday{
//	        {Name: "New Year's Day", Rule: &schedule.HolidayRule{...}},
//	        {Name: "Independence Day", Rule: &schedule.HolidayRule{...}},
//	        {Name: "Thanksgiving", Rule: &schedule.HolidayRule{...}},
//	        // ... more holidays
//	    },
//	    WeekendDays: []int32{6, 7},  // Saturday, Sunday
//	    Timezone: "America/New_York",
//	}
type BusinessCalendar struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// calendar_id: Unique identifier for this calendar.
	// Referenced by BusinessDaysRule.business_calendar_id.
	CalendarId string `protobuf:"bytes,1,opt,name=calendar_id,json=calendarId,proto3" json:"calendar_id,omitempty"`
	// name: Human-readable name.
	// Example: "US Federal Holidays", "UK Bank Holidays", "ACME Corp Custom Calendar"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// description: Optional detailed description.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// holidays: List of holidays (days to skip for business day schedules).
	// Can be fixed dates (Dec 25) or relative (first Monday in May).
	Holidays []*Holiday `protobuf:"bytes,4,rep,name=holidays,proto3" json:"holidays,omitempty"`
	// weekend_days: Days considered weekends (1=Monday, 7=Sunday).
	// Common values:
	//
	//	[6, 7] = Saturday, Sunday (most countries)
	//	[5, 6] = Friday, Saturday (some Middle Eastern countries)
	//	[7] = Sunday only
	WeekendDays []int32 `protobuf:"varint,5,rep,packed,name=weekend_days,json=weekendDays,proto3" json:"weekend_days,omitempty"`
	// timezone: IANA timezone for this calendar.
	// Affects date boundaries for holidays.
	Timezone      string `protobuf:"bytes,6,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BusinessCalendar) Reset() {
	*x = BusinessCalendar{}
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BusinessCalendar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessCalendar) ProtoMessage() {}

func (x *BusinessCalendar) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessCalendar.ProtoReflect.Descriptor instead.
func (*BusinessCalendar) Descriptor() ([]byte, []int) {
	return file_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{11}
}

func (x *BusinessCalendar) GetCalendarId() string {
	if x != nil {
		return x.CalendarId
	}
	return ""
}

func (x *BusinessCalendar) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BusinessCalendar) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BusinessCalendar) GetHolidays() []*Holiday {
	if x != nil {
		return x.Holidays
	}
	return nil
}

func (x *BusinessCalendar) GetWeekendDays() []int32 {
	if x != nil {
		return x.WeekendDays
	}
	return nil
}

func (x *BusinessCalendar) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

// Holiday represents a non-working day in a BusinessCalendar.
//
// Examples:
//
//	Fixed date holiday (Christmas):
//	  {
//	    name: "Christmas",
//	    recurring_yearly: true,
//	    rule: {fixed: {month: 12, day: 25}}
//	  }
//
//	Relative date holiday (US Thanksgiving - 4th Thursday of November):
//	  {
//	    name: "Thanksgiving",
//	    recurring_yearly: true,
//	    rule: {relative: {month: 11, weekday: 4, occurrence: 4}}
//	  }
//
//	Easter-based holiday (Good Friday - 2 days before Easter):
//	  {
//	    name: "Good Friday",
//	    recurring_yearly: true,
//	    rule: {easter_offset: {days_offset: -2}}
//	  }
type Holiday struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name: Holiday name (e.g., "New Year's Day", "Memorial Day").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// date: Specific date for one-time holidays.
	// For recurring holidays, use rule instead.
	Date *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	// recurring_yearly: If true, this holiday repeats every year.
	// Requires rule to be set to determine the date each year.
	RecurringYearly bool `protobuf:"varint,3,opt,name=recurring_yearly,json=recurringYearly,proto3" json:"recurring_yearly,omitempty"`
	// rule: Logic for calculating holiday date.
	// Required if recurring_yearly = true.
	Rule          *HolidayRule `protobuf:"bytes,4,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Holiday) Reset() {
	*x = Holiday{}
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Holiday) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Holiday) ProtoMessage() {}

func (x *Holiday) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Holiday.ProtoReflect.Descriptor instead.
func (*Holiday) Descriptor() ([]byte, []int) {
	return file_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{12}
}

func (x *Holiday) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Holiday) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *Holiday) GetRecurringYearly() bool {
	if x != nil {
		return x.RecurringYearly
	}
	return false
}

func (x *Holiday) GetRule() *HolidayRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

// HolidayRule defines how to calculate a holiday's date.
type HolidayRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Choose one rule type based on holiday pattern.
	//
	// Types that are valid to be assigned to Rule:
	//
	//	*HolidayRule_Fixed
	//	*HolidayRule_Relative
	//	*HolidayRule_EasterOffset
	Rule          isHolidayRule_Rule `protobuf_oneof:"rule"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HolidayRule) Reset() {
	*x = HolidayRule{}
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolidayRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolidayRule) ProtoMessage() {}

func (x *HolidayRule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HolidayRule.ProtoReflect.Descriptor instead.
func (*HolidayRule) Descriptor() ([]byte, []int) {
	return file_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{13}
}

func (x *HolidayRule) GetRule() isHolidayRule_Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

func (x *HolidayRule) GetFixed() *FixedDate {
	if x != nil {
		if x, ok := x.Rule.(*HolidayRule_Fixed); ok {
			return x.Fixed
		}
	}
	return nil
}

func (x *HolidayRule) GetRelative() *RelativeDate {
	if x != nil {
		if x, ok := x.Rule.(*HolidayRule_Relative); ok {
			return x.Relative
		}
	}
	return nil
}

func (x *HolidayRule) GetEasterOffset() *EasterOffset {
	if x != nil {
		if x, ok := x.Rule.(*HolidayRule_EasterOffset); ok {
			return x.EasterOffset
		}
	}
	return nil
}

type isHolidayRule_Rule interface {
	isHolidayRule_Rule()
}

type HolidayRule_Fixed struct {
	Fixed *FixedDate `protobuf:"bytes,1,opt,name=fixed,proto3,oneof"` // Same date every year (Dec 25)
}

type HolidayRule_Relative struct {
	Relative *RelativeDate `protobuf:"bytes,2,opt,name=relative,proto3,oneof"` // Relative to month (first Monday in May)
}

type HolidayRule_EasterOffset struct {
	EasterOffset *EasterOffset `protobuf:"bytes,3,opt,name=easter_offset,json=easterOffset,proto3,oneof"` // Days offset from Easter
}

func (*HolidayRule_Fixed) isHolidayRule_Rule() {}

func (*HolidayRule_Relative) isHolidayRule_Rule() {}

func (*HolidayRule_EasterOffset) isHolidayRule_Rule() {}

// FixedDate represents a holiday on the same calendar date every year.
//
// Examples:
//
//	Christmas: {month: 12, day: 25}
//	Independence Day (US): {month: 7, day: 4}
//	New Year's Day: {month: 1, day: 1}
type FixedDate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// month: Month (1=January, 12=December).
	Month int32 `protobuf:"varint,1,opt,name=month,proto3" json:"month,omitempty"`
	// day: Day of month (1-31).
	Day           int32 `protobuf:"varint,2,opt,name=day,proto3" json:"day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FixedDate) Reset() {
	*x = FixedDate{}
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FixedDate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FixedDate) ProtoMessage() {}

func (x *FixedDate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FixedDate.ProtoReflect.Descriptor instead.
func (*FixedDate) Descriptor() ([]byte, []int) {
	return file_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{14}
}

func (x *FixedDate) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *FixedDate) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

// RelativeDate represents a holiday defined by weekday occurrence in a month.
//
// Examples:
//
//	Memorial Day (US): Last Monday of May
//	  {month: 5, weekday: 1, occurrence: -1}
//
//	Thanksgiving (US): 4th Thursday of November
//	  {month: 11, weekday: 4, occurrence: 4}
//
//	Labor Day (US): First Monday of September
//	  {month: 9, weekday: 1, occurrence: 1}
type RelativeDate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// month: Month (1=January, 12=December).
	Month int32 `protobuf:"varint,1,opt,name=month,proto3" json:"month,omitempty"`
	// weekday: Day of week (1=Monday, 7=Sunday, ISO 8601).
	Weekday int32 `protobuf:"varint,2,opt,name=weekday,proto3" json:"weekday,omitempty"`
	// occurrence: Which occurrence in the month.
	// 1 = first, 2 = second, 3 = third, 4 = fourth
	// -1 = last (useful when week count varies by month)
	Occurrence    int32 `protobuf:"varint,3,opt,name=occurrence,proto3" json:"occurrence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelativeDate) Reset() {
	*x = RelativeDate{}
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelativeDate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelativeDate) ProtoMessage() {}

func (x *RelativeDate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelativeDate.ProtoReflect.Descriptor instead.
func (*RelativeDate) Descriptor() ([]byte, []int) {
	return file_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{15}
}

func (x *RelativeDate) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *RelativeDate) GetWeekday() int32 {
	if x != nil {
		return x.Weekday
	}
	return 0
}

func (x *RelativeDate) GetOccurrence() int32 {
	if x != nil {
		return x.Occurrence
	}
	return 0
}

// EasterOffset represents holidays calculated relative to Easter Sunday.
// Easter date varies year-to-year based on lunar calendar.
//
// Examples:
//
//	Good Friday: {days_offset: -2}
//	Easter Monday: {days_offset: 1}
//	Ascension Day: {days_offset: 39}
//	Pentecost: {days_offset: 49}
type EasterOffset struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// days_offset: Days to add to Easter Sunday.
	// Negative = before Easter, positive = after Easter, 0 = Easter itself.
	DaysOffset    int32 `protobuf:"varint,1,opt,name=days_offset,json=daysOffset,proto3" json:"days_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EasterOffset) Reset() {
	*x = EasterOffset{}
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EasterOffset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EasterOffset) ProtoMessage() {}

func (x *EasterOffset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EasterOffset.ProtoReflect.Descriptor instead.
func (*EasterOffset) Descriptor() ([]byte, []int) {
	return file_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{16}
}

func (x *EasterOffset) GetDaysOffset() int32 {
	if x != nil {
		return x.DaysOffset
	}
	return 0
}

// CalendarException modifies schedule behavior for a specific date.
// Use for one-off changes without modifying the core schedule.
//
// Examples:
//
//	Skip execution during maintenance:
//	  {date: "2024-06-15", type: SKIP, reason: "System maintenance"}
//
//	Reschedule monthly report when month-end is holiday:
//	  {date: "2024-12-31", type: RESCHEDULE, reschedule_to: "2024-12-30", reason: "New Year's Eve"}
//
//	Add extra execution for special event:
//	  {date: "2024-11-29", type: EXTRA, extra_times: [{hour: 14}], reason: "Black Friday promotions"}
type CalendarException struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// date: Date this exception applies to.
	Date *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	// type: What kind of exception to apply.
	Type CalendarException_ExceptionType `protobuf:"varint,2,opt,name=type,proto3,enum=nzovu.api.schedule.v1.CalendarException_ExceptionType" json:"type,omitempty"`
	// reschedule_to: Target date for RESCHEDULE exceptions.
	// Required if type = RESCHEDULE.
	RescheduleTo *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=reschedule_to,json=rescheduleTo,proto3" json:"reschedule_to,omitempty"`
	// extra_times: Additional execution times for EXTRA exceptions.
	// Applied in addition to regular schedule.
	// Required if type = EXTRA.
	ExtraTimes []*TimeOfDay `protobuf:"bytes,4,rep,name=extra_times,json=extraTimes,proto3" json:"extra_times,omitempty"`
	// reason: Optional explanation for this exception.
	// Useful for documentation and auditing.
	// Example: "System maintenance", "Holiday adjustment", "Special event"
	Reason        string `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalendarException) Reset() {
	*x = CalendarException{}
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalendarException) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalendarException) ProtoMessage() {}

func (x *CalendarException) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalendarException.ProtoReflect.Descriptor instead.
func (*CalendarException) Descriptor() ([]byte, []int) {
	return file_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{17}
}

func (x *CalendarException) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *CalendarException) GetType() CalendarException_ExceptionType {
	if x != nil {
		return x.Type
	}
	return CalendarException_SKIP
}

func (x *CalendarException) GetRescheduleTo() *timestamppb.Timestamp {
	if x != nil {
		return x.RescheduleTo
	}
	return nil
}

func (x *CalendarException) GetExtraTimes() []*TimeOfDay {
	if x != nil {
		return x.ExtraTimes
	}
	return nil
}

func (x *CalendarException) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Metadata contains schedule configuration and execution state.
type Schedule_Metadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// payload: Template payload for messages created by this schedule.
	// Each scheduled execution creates a new message with this payload.
	// You can include template variables that get resolved at execution time.
	Payload *v11.Payload            `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	State   Schedule_Metadata_State `protobuf:"varint,2,opt,name=state,proto3,enum=nzovu.api.schedule.v1.Schedule_Metadata_State" json:"state,omitempty"`
	// schedule_config: Defines WHEN messages are posted.
	// Choose one: cron_schedule (simple) or calendar_schedule (advanced).
	//
	// Types that are valid to be assigned to ScheduleConfig:
	//
	//	*Schedule_Metadata_CronSchedule
	//	*Schedule_Metadata_CalendarSchedule
	ScheduleConfig isSchedule_Metadata_ScheduleConfig `protobuf_oneof:"schedule_config"`
	// queue_name: Target queue where scheduled messages are posted.
	// Must be an existing queue.
	// Messages inherit queue's retry, lease, and DLQ settings.
	QueueName string `protobuf:"bytes,4,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	// message_ids: Deprecated legacy execution IDs.
	// New executions are available through GetScheduleHistory, which retains
	// immutable message snapshots without growing this schedule record.
	//
	// Deprecated: Marked as deprecated in proto/schedule/v1/schedule.proto.
	MessageIds []string `protobuf:"bytes,5,rep,name=message_ids,json=messageIds,proto3" json:"message_ids,omitempty"`
	// next_run: When this schedule will execute next.
	// Auto-calculated by Nzovu based on schedule_config.
	// Read-only from client perspective.
	NextRun *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=next_run,json=nextRun,proto3" json:"next_run,omitempty"`
	// last_run: When this schedule last executed.
	// Null if never executed. Useful for monitoring schedule health.
	LastRun *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_run,json=lastRun,proto3" json:"last_run,omitempty"`
	// created_at: When this schedule was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// updated_at: When this schedule was last modified.
	// Updates when pausing, resuming, or changing configuration.
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// state_message: Human-readable status or error message.
	// Contains error details when state = ERRORED.
	// Example: "Failed to post message: queue 'reports' not found"
	StateMessage string `protobuf:"bytes,11,opt,name=state_message,json=stateMessage,proto3" json:"state_message,omitempty"`
	// priority: Priority for messages created by this schedule.
	// Inherited by posted messages unless message specifies otherwise.
	// Values: 4 (high), 2 (normal), 0 (low).
	Priority int64 `protobuf:"varint,12,opt,name=priority,proto3" json:"priority,omitempty"`
	// has_max_messages: If true, enforces max_messages limit.
	// Safety feature to prevent runaway schedules.
	HasMaxMessages bool `protobuf:"varint,13,opt,name=has_max_messages,json=hasMaxMessages,proto3" json:"has_max_messages,omitempty"`
	// max_messages: Maximum total messages this schedule can create.
	// When reached, schedule automatically moves to PAUSED state.
	// Reset by calling ResumeSchedule. Set to 0 for unlimited.
	// Use for: one-time campaigns, limited batch jobs, testing.
	MaxMessages int64 `protobuf:"varint,14,opt,name=max_messages,json=maxMessages,proto3" json:"max_messages,omitempty"`
	// lease_duration: Override default lease duration for scheduled messages.
	// If not set, uses queue's default lease_duration.
	// Useful when scheduled tasks need different processing time than queue default.
	LeaseDuration *durationpb.Duration `protobuf:"bytes,15,opt,name=lease_duration,json=leaseDuration,proto3" json:"lease_duration,omitempty"`
	// Deprecated: calendar_schedule.timezone is the canonical timezone.
	// If supplied for compatibility, it must match calendar_schedule.timezone.
	//
	// Deprecated: Marked as deprecated in proto/schedule/v1/schedule.proto.
	Timezone string `protobuf:"bytes,17,opt,name=timezone,proto3" json:"timezone,omitempty"`
	// next_runs: Precomputed upcoming execution times (for preview/validation).
	// Populated by PreviewSchedule API or ValidateSchedule API.
	// Shows next N execution times to verify schedule behaves as expected.
	NextRuns []*timestamppb.Timestamp `protobuf:"bytes,18,rep,name=next_runs,json=nextRuns,proto3" json:"next_runs,omitempty"`
	// headers: Optional ordered headers copied to every message created by
	// this schedule. Values are opaque bytes and duplicate keys are allowed.
	Headers       []*v1.Message_Metadata_Header `protobuf:"bytes,19,rep,name=headers,proto3" json:"headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schedule_Metadata) Reset() {
	*x = Schedule_Metadata{}
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schedule_Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schedule_Metadata) ProtoMessage() {}

func (x *Schedule_Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schedule_Metadata.ProtoReflect.Descriptor instead.
func (*Schedule_Metadata) Descriptor() ([]byte, []int) {
	return file_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Schedule_Metadata) GetPayload() *v11.Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Schedule_Metadata) GetState() Schedule_Metadata_State {
	if x != nil {
		return x.State
	}
	return Schedule_Metadata_SCHEDULED
}

func (x *Schedule_Metadata) GetScheduleConfig() isSchedule_Metadata_ScheduleConfig {
	if x != nil {
		return x.ScheduleConfig
	}
	return nil
}

func (x *Schedule_Metadata) GetCronSchedule() string {
	if x != nil {
		if x, ok := x.ScheduleConfig.(*Schedule_Metadata_CronSchedule); ok {
			return x.CronSchedule
		}
	}
	return ""
}

func (x *Schedule_Metadata) GetCalendarSchedule() *CalendarSchedule {
	if x != nil {
		if x, ok := x.ScheduleConfig.(*Schedule_Metadata_CalendarSchedule); ok {
			return x.CalendarSchedule
		}
	}
	return nil
}

func (x *Schedule_Metadata) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

// Deprecated: Marked as deprecated in proto/schedule/v1/schedule.proto.
func (x *Schedule_Metadata) GetMessageIds() []string {
	if x != nil {
		return x.MessageIds
	}
	return nil
}

func (x *Schedule_Metadata) GetNextRun() *timestamppb.Timestamp {
	if x != nil {
		return x.NextRun
	}
	return nil
}

func (x *Schedule_Metadata) GetLastRun() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRun
	}
	return nil
}

func (x *Schedule_Metadata) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Schedule_Metadata) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Schedule_Metadata) GetStateMessage() string {
	if x != nil {
		return x.StateMessage
	}
	return ""
}

func (x *Schedule_Metadata) GetPriority() int64 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Schedule_Metadata) GetHasMaxMessages() bool {
	if x != nil {
		return x.HasMaxMessages
	}
	return false
}

func (x *Schedule_Metadata) GetMaxMessages() int64 {
	if x != nil {
		return x.MaxMessages
	}
	return 0
}

func (x *Schedule_Metadata) GetLeaseDuration() *durationpb.Duration {
	if x != nil {
		return x.LeaseDuration
	}
	return nil
}

// Deprecated: Marked as deprecated in proto/schedule/v1/schedule.proto.
func (x *Schedule_Metadata) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *Schedule_Metadata) GetNextRuns() []*timestamppb.Timestamp {
	if x != nil {
		return x.NextRuns
	}
	return nil
}

func (x *Schedule_Metadata) GetHeaders() []*v1.Message_Metadata_Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

type isSchedule_Metadata_ScheduleConfig interface {
	isSchedule_Metadata_ScheduleConfig()
}

type Schedule_Metadata_CronSchedule struct {
	// cron_schedule: Unix cron expression (legacy, still supported).
	// Format: "minute hour day month weekday"
	// Examples:
	//
	//	"0 9 * * 1-5"     = 9 AM weekdays
	//	"0 */4 * * *"     = every 4 hours
	//	"0 0 1 * *"       = first day of month
	//	"*/15 * * * *"    = every 15 minutes
	//
	// Limitation: No timezone support, no business calendar logic.
	CronSchedule string `protobuf:"bytes,3,opt,name=cron_schedule,json=cronSchedule,proto3,oneof"`
}

type Schedule_Metadata_CalendarSchedule struct {
	// calendar_schedule: Rich business calendar support (recommended).
	// Supports:
	// - Business days, holidays, custom calendars
	// - Complex rules (nth weekday of month, last Friday, quarterly)
	// - Timezone-aware scheduling
	// - Exception handling (skip dates, reschedule)
	// See CalendarSchedule message for full capabilities.
	CalendarSchedule *CalendarSchedule `protobuf:"bytes,16,opt,name=calendar_schedule,json=calendarSchedule,proto3,oneof"`
}

func (*Schedule_Metadata_CronSchedule) isSchedule_Metadata_ScheduleConfig() {}

func (*Schedule_Metadata_CalendarSchedule) isSchedule_Metadata_ScheduleConfig() {}

type ScheduleHistory_Execution struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// message_id: Identifier assigned to the generated message.
	MessageId string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// executed_at: Scheduled execution time recorded by the processor.
	ExecutedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=executed_at,json=executedAt,proto3" json:"executed_at,omitempty"`
	// success: Whether the schedule execution created its message.
	Success bool `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	// error_message: Execution failure detail when success is false.
	ErrorMessage string `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// message: Immutable snapshot of the generated message. This remains
	// available after the live message is removed by its retention policy.
	Message       *v1.Message `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleHistory_Execution) Reset() {
	*x = ScheduleHistory_Execution{}
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleHistory_Execution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleHistory_Execution) ProtoMessage() {}

func (x *ScheduleHistory_Execution) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedule_v1_schedule_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleHistory_Execution.ProtoReflect.Descriptor instead.
func (*ScheduleHistory_Execution) Descriptor() ([]byte, []int) {
	return file_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ScheduleHistory_Execution) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ScheduleHistory_Execution) GetExecutedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExecutedAt
	}
	return nil
}

func (x *ScheduleHistory_Execution) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ScheduleHistory_Execution) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ScheduleHistory_Execution) GetMessage() *v1.Message {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_proto_schedule_v1_schedule_proto protoreflect.FileDescriptor

const file_proto_schedule_v1_schedule_proto_rawDesc = "" +
	"\n" +
	" proto/schedule/v1/schedule.proto\x12\x15nzovu.api.schedule.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cproto/common/v1/common.proto\x1a\x1eproto/message/v1/message.proto\"\xfe\b\n" +
	"\bSchedule\x12\x1f\n" +
	"\vschedule_id\x18\x01 \x01(\tR\n" +
	"scheduleId\x12D\n" +
	"\bmetadata\x18\x02 \x01(\v2(.nzovu.api.schedule.v1.Schedule.MetadataR\bmetadata\x1a\x8a\b\n" +
	"\bMetadata\x126\n" +
	"\apayload\x18\x01 \x01(\v2\x1c.nzovu.api.common.v1.PayloadR\apayload\x12D\n" +
	"\x05state\x18\x02 \x01(\x0e2..nzovu.api.schedule.v1.Schedule.Metadata.StateR\x05state\x12%\n" +
	"\rcron_schedule\x18\x03 \x01(\tH\x00R\fcronSchedule\x12V\n" +
	"\x11calendar_schedule\x18\x10 \x01(\v2'.nzovu.api.schedule.v1.CalendarScheduleH\x00R\x10calendarSchedule\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x04 \x01(\tR\tqueueName\x12#\n" +
	"\vmessage_ids\x18\x05 \x03(\tB\x02\x18\x01R\n" +
	"messageIds\x125\n" +
	"\bnext_run\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\anextRun\x125\n" +
	"\blast_run\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\alastRun\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12#\n" +
	"\rstate_message\x18\v \x01(\tR\fstateMessage\x12\x1a\n" +
	"\bpriority\x18\f \x01(\x03R\bpriority\x12(\n" +
	"\x10has_max_messages\x18\r \x01(\bR\x0ehasMaxMessages\x12!\n" +
	"\fmax_messages\x18\x0e \x01(\x03R\vmaxMessages\x12@\n" +
	"\x0elease_duration\x18\x0f \x01(\v2\x19.google.protobuf.DurationR\rleaseDuration\x12\x1e\n" +
	"\btimezone\x18\x11 \x01(\tB\x02\x18\x01R\btimezone\x127\n" +
	"\tnext_runs\x18\x12 \x03(\v2\x1a.google.protobuf.TimestampR\bnextRuns\x12G\n" +
	"\aheaders\x18\x13 \x03(\v2-.nzovu.api.message.v1.Message.Metadata.HeaderR\aheaders\"=\n" +
	"\x05State\x12\r\n" +
	"\tSCHEDULED\x10\x00\x12\f\n" +
	"\bCANCELED\x10\x01\x12\v\n" +
	"\aERRORED\x10\x02\x12\n" +
	"\n" +
	"\x06PAUSED\x10\x03B\x11\n" +
	"\x0fschedule_configJ\x04\b\n" +
	"\x10\vR\x0fexclusivity_key\"\x85\x05\n" +
	"\x0fScheduleHistory\x129\n" +
	"\bmessages\x18\x01 \x03(\v2\x1d.nzovu.api.message.v1.MessageR\bmessages\x12\x1f\n" +
	"\vschedule_id\x18\x02 \x01(\tR\n" +
	"scheduleId\x125\n" +
	"\bnext_run\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\anextRun\x125\n" +
	"\blast_run\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\alastRun\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12P\n" +
	"\n" +
	"executions\x18\a \x03(\v20.nzovu.api.schedule.v1.ScheduleHistory.ExecutionR\n" +
	"executions\x1a\xdf\x01\n" +
	"\tExecution\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12;\n" +
	"\vexecuted_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"executedAt\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x127\n" +
	"\amessage\x18\x05 \x01(\v2\x1d.nzovu.api.message.v1.MessageR\amessage\"\xb2\x03\n" +
	"\x10CalendarSchedule\x12H\n" +
	"\x04type\x18\x01 \x01(\x0e24.nzovu.api.schedule.v1.CalendarSchedule.ScheduleTypeR\x04type\x129\n" +
	"\x05rules\x18\x02 \x03(\v2#.nzovu.api.schedule.v1.CalendarRuleR\x05rules\x12\x1a\n" +
	"\btimezone\x18\x03 \x01(\tR\btimezone\x12T\n" +
	"\x11business_calendar\x18\x04 \x01(\v2'.nzovu.api.schedule.v1.BusinessCalendarR\x10businessCalendar\x12H\n" +
	"\n" +
	"exceptions\x18\x05 \x03(\v2(.nzovu.api.schedule.v1.CalendarExceptionR\n" +
	"exceptions\"]\n" +
	"\fScheduleType\x12\v\n" +
	"\aMONTHLY\x10\x00\x12\n" +
	"\n" +
	"\x06WEEKLY\x10\x01\x12\t\n" +
	"\x05DAILY\x10\x02\x12\n" +
	"\n" +
	"\x06YEARLY\x10\x03\x12\x11\n" +
	"\rBUSINESS_DAYS\x10\x04\x12\n" +
	"\n" +
	"\x06CUSTOM\x10\x05\"\xda\x04\n" +
	"\fCalendarRule\x12>\n" +
	"\amonthly\x18\x01 \x01(\v2\".nzovu.api.schedule.v1.MonthlyRuleH\x00R\amonthly\x12;\n" +
	"\x06weekly\x18\x02 \x01(\v2!.nzovu.api.schedule.v1.WeeklyRuleH\x00R\x06weekly\x128\n" +
	"\x05daily\x18\x03 \x01(\v2 .nzovu.api.schedule.v1.DailyRuleH\x00R\x05daily\x12;\n" +
	"\x06yearly\x18\x04 \x01(\v2!.nzovu.api.schedule.v1.YearlyRuleH\x00R\x06yearly\x12N\n" +
	"\rbusiness_days\x18\x05 \x01(\v2'.nzovu.api.schedule.v1.BusinessDaysRuleH\x00R\fbusinessDays\x12;\n" +
	"\x06custom\x18\x06 \x01(\v2!.nzovu.api.schedule.v1.CustomRuleH\x00R\x06custom\x12I\n" +
	"\x0fexecution_times\x18\a \x03(\v2 .nzovu.api.schedule.v1.TimeOfDayR\x0eexecutionTimes\x129\n" +
	"\n" +
	"valid_from\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tvalidFrom\x12;\n" +
	"\vvalid_until\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"validUntilB\x06\n" +
	"\x04rule\"\xfc\x01\n" +
	"\vMonthlyRule\x12E\n" +
	"\bday_type\x18\x01 \x01(\x0e2*.nzovu.api.schedule.v1.MonthlyRule.DayTypeR\adayType\x12\x1b\n" +
	"\tday_value\x18\x02 \x01(\x05R\bdayValue\x12\x1e\n" +
	"\n" +
	"occurrence\x18\x03 \x01(\x05R\n" +
	"occurrence\x12\x16\n" +
	"\x06months\x18\x04 \x03(\x05R\x06months\"Q\n" +
	"\aDayType\x12\x10\n" +
	"\fDAY_OF_MONTH\x10\x00\x12\x14\n" +
	"\x10WEEKDAY_OF_MONTH\x10\x01\x12\x10\n" +
	"\fLAST_WEEKDAY\x10\x02\x12\f\n" +
	"\bLAST_DAY\x10\x03\"\x8e\x01\n" +
	"\n" +
	"WeeklyRule\x12 \n" +
	"\fdays_of_week\x18\x01 \x03(\x05R\n" +
	"daysOfWeek\x12#\n" +
	"\rweek_interval\x18\x02 \x01(\x05R\fweekInterval\x129\n" +
	"\n" +
	"start_week\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartWeek\"\x8e\x01\n" +
	"\tDailyRule\x12!\n" +
	"\fday_interval\x18\x01 \x01(\x05R\vdayInterval\x12#\n" +
	"\rweekdays_only\x18\x02 \x01(\bR\fweekdaysOnly\x129\n" +
	"\n" +
	"start_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\"e\n" +
	"\n" +
	"YearlyRule\x12\x14\n" +
	"\x05month\x18\x01 \x01(\x05R\x05month\x12\x10\n" +
	"\x03day\x18\x02 \x01(\x05R\x03day\x12/\n" +
	"\x14adjust_for_leap_year\x18\x03 \x01(\bR\x11adjustForLeapYear\"c\n" +
	"\x10BusinessDaysRule\x120\n" +
	"\x14business_calendar_id\x18\x01 \x01(\tR\x12businessCalendarId\x12\x1d\n" +
	"\n" +
	"day_offset\x18\x02 \x01(\x05R\tdayOffset\"\xdb\x01\n" +
	"\n" +
	"CustomRule\x12\x1e\n" +
	"\n" +
	"expression\x18\x01 \x01(\tR\n" +
	"expression\x12\x1b\n" +
	"\trule_type\x18\x02 \x01(\tR\bruleType\x12Q\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v21.nzovu.api.schedule.v1.CustomRule.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"O\n" +
	"\tTimeOfDay\x12\x12\n" +
	"\x04hour\x18\x01 \x01(\x05R\x04hour\x12\x16\n" +
	"\x06minute\x18\x02 \x01(\x05R\x06minute\x12\x16\n" +
	"\x06second\x18\x03 \x01(\x05R\x06second\"\xe4\x01\n" +
	"\x10BusinessCalendar\x12\x1f\n" +
	"\vcalendar_id\x18\x01 \x01(\tR\n" +
	"calendarId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12:\n" +
	"\bholidays\x18\x04 \x03(\v2\x1e.nzovu.api.schedule.v1.HolidayR\bholidays\x12!\n" +
	"\fweekend_days\x18\x05 \x03(\x05R\vweekendDays\x12\x1a\n" +
	"\btimezone\x18\x06 \x01(\tR\btimezone\"\xb0\x01\n" +
	"\aHoliday\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12.\n" +
	"\x04date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12)\n" +
	"\x10recurring_yearly\x18\x03 \x01(\bR\x0frecurringYearly\x126\n" +
	"\x04rule\x18\x04 \x01(\v2\".nzovu.api.schedule.v1.HolidayRuleR\x04rule\"\xde\x01\n" +
	"\vHolidayRule\x128\n" +
	"\x05fixed\x18\x01 \x01(\v2 .nzovu.api.schedule.v1.FixedDateH\x00R\x05fixed\x12A\n" +
	"\brelative\x18\x02 \x01(\v2#.nzovu.api.schedule.v1.RelativeDateH\x00R\brelative\x12J\n" +
	"\reaster_offset\x18\x03 \x01(\v2#.nzovu.api.schedule.v1.EasterOffsetH\x00R\feasterOffsetB\x06\n" +
	"\x04rule\"3\n" +
	"\tFixedDate\x12\x14\n" +
	"\x05month\x18\x01 \x01(\x05R\x05month\x12\x10\n" +
	"\x03day\x18\x02 \x01(\x05R\x03day\"^\n" +
	"\fRelativeDate\x12\x14\n" +
	"\x05month\x18\x01 \x01(\x05R\x05month\x12\x18\n" +
	"\aweekday\x18\x02 \x01(\x05R\aweekday\x12\x1e\n" +
	"\n" +
	"occurrence\x18\x03 \x01(\x05R\n" +
	"occurrence\"/\n" +
	"\fEasterOffset\x12\x1f\n" +
	"\vdays_offset\x18\x01 \x01(\x05R\n" +
	"daysOffset\"\xe1\x02\n" +
	"\x11CalendarException\x12.\n" +
	"\x04date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12J\n" +
	"\x04type\x18\x02 \x01(\x0e26.nzovu.api.schedule.v1.CalendarException.ExceptionTypeR\x04type\x12?\n" +
	"\rreschedule_to\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\frescheduleTo\x12A\n" +
	"\vextra_times\x18\x04 \x03(\v2 .nzovu.api.schedule.v1.TimeOfDayR\n" +
	"extraTimes\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"4\n" +
	"\rExceptionType\x12\b\n" +
	"\x04SKIP\x10\x00\x12\x0e\n" +
	"\n" +
	"RESCHEDULE\x10\x01\x12\t\n" +
	"\x05EXTRA\x10\x02B4Z2github.com/adrien19/nzovu/api/schedule/v1;scheduleb\x06proto3"

var (
	file_proto_schedule_v1_schedule_proto_rawDescOnce sync.Once
	file_proto_schedule_v1_schedule_proto_rawDescData []byte
)

func file_proto_schedule_v1_schedule_proto_rawDescGZIP() []byte {
	file_proto_schedule_v1_schedule_proto_rawDescOnce.Do(func() {
		file_proto_schedule_v1_schedule_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_schedule_v1_schedule_proto_rawDesc), len(file_proto_schedule_v1_schedule_proto_rawDesc)))
	})
	return file_proto_schedule_v1_schedule_proto_rawDescData
}

var file_proto_schedule_v1_schedule_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_schedule_v1_schedule_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_schedule_v1_schedule_proto_goTypes = []any{
	(Schedule_Metadata_State)(0),         // 0: nzovu.api.schedule.v1.Schedule.Metadata.State
	(CalendarSchedule_ScheduleType)(0),   // 1: nzovu.api.schedule.v1.CalendarSchedule.ScheduleType
	(MonthlyRule_DayType)(0),             // 2: nzovu.api.schedule.v1.MonthlyRule.DayType
	(CalendarException_ExceptionType)(0), // 3: nzovu.api.schedule.v1.CalendarException.ExceptionType
	(*Schedule)(nil),                     // 4: nzovu.api.schedule.v1.Schedule
	(*ScheduleHistory)(nil),              // 5: nzovu.api.schedule.v1.ScheduleHistory
	(*CalendarSchedule)(nil),             // 6: nzovu.api.schedule.v1.CalendarSchedule
	(*CalendarRule)(nil),                 // 7: nzovu.api.schedule.v1.CalendarRule
	(*MonthlyRule)(nil),                  // 8: nzovu.api.schedule.v1.MonthlyRule
	(*WeeklyRule)(nil),                   // 9: nzovu.api.schedule.v1.WeeklyRule
	(*DailyRule)(nil),                    // 10: nzovu.api.schedule.v1.DailyRule
	(*YearlyRule)(nil),                   // 11: nzovu.api.schedule.v1.YearlyRule
	(*BusinessDaysRule)(nil),             // 12: nzovu.api.schedule.v1.BusinessDaysRule
	(*CustomRule)(nil),                   // 13: nzovu.api.schedule.v1.CustomRule
	(*TimeOfDay)(nil),                    // 14: nzovu.api.schedule.v1.TimeOfDay
	(*BusinessCalendar)(nil),             // 15: nzovu.api.schedule.v1.BusinessCalendar
	(*Holiday)(nil),                      // 16: nzovu.api.schedule.v1.Holiday
	(*HolidayRule)(nil),                  // 17: nzovu.api.schedule.v1.HolidayRule
	(*FixedDate)(nil),                    // 18: nzovu.api.schedule.v1.FixedDate
	(*RelativeDate)(nil),                 // 19: nzovu.api.schedule.v1.RelativeDate
	(*EasterOffset)(nil),                 // 20: nzovu.api.schedule.v1.EasterOffset
	(*CalendarException)(nil),            // 21: nzovu.api.schedule.v1.CalendarException
	(*Schedule_Metadata)(nil),            // 22: nzovu.api.schedule.v1.Schedule.Metadata
	(*ScheduleHistory_Execution)(nil),    // 23: nzovu.api.schedule.v1.ScheduleHistory.Execution
	nil,                                  // 24: nzovu.api.schedule.v1.CustomRule.ParametersEntry
	(*v1.Message)(nil),                   // 25: nzovu.api.message.v1.Message
	(*timestamppb.Timestamp)(nil),        // 26: google.protobuf.Timestamp
	(*v11.Payload)(nil),                  // 27: nzovu.api.common.v1.Payload
	(*durationpb.Duration)(nil),          // 28: google.protobuf.Duration
	(*v1.Message_Metadata_Header)(nil),   // 29: nzovu.api.message.v1.Message.Metadata.Header
}
var file_proto_schedule_v1_schedule_proto_depIdxs = []int32{
	22, // 0: nzovu.api.schedule.v1.Schedule.metadata:type_name -> nzovu.api.schedule.v1.Schedule.Metadata
	25, // 1: nzovu.api.schedule.v1.ScheduleHistory.messages:type_name -> nzovu.api.message.v1.Message
	26, // 2: nzovu.api.schedule.v1.ScheduleHistory.next_run:type_name -> google.protobuf.Timestamp
	26, // 3: nzovu.api.schedule.v1.ScheduleHistory.last_run:type_name -> google.protobuf.Timestamp
	26, // 4: nzovu.api.schedule.v1.ScheduleHistory.created_at:type_name -> google.protobuf.Timestamp
	26, // 5: nzovu.api.schedule.v1.ScheduleHistory.updated_at:type_name -> google.protobuf.Timestamp
	23, // 6: nzovu.api.schedule.v1.ScheduleHistory.executions:type_name -> nzovu.api.schedule.v1.ScheduleHistory.Execution
	1,  // 7: nzovu.api.schedule.v1.CalendarSchedule.type:type_name -> nzovu.api.schedule.v1.CalendarSchedule.ScheduleType
	7,  // 8: nzovu.api.schedule.v1.CalendarSchedule.rules:type_name -> nzovu.api.schedule.v1.CalendarRule
	15, // 9: nzovu.api.schedule.v1.CalendarSchedule.business_calendar:type_name -> nzovu.api.schedule.v1.BusinessCalendar
	21, // 10: nzovu.api.schedule.v1.CalendarSchedule.exceptions:type_name -> nzovu.api.schedule.v1.CalendarException
	8,  // 11: nzovu.api.schedule.v1.CalendarRule.monthly:type_name -> nzovu.api.schedule.v1.MonthlyRule
	9,  // 12: nzovu.api.schedule.v1.CalendarRule.weekly:type_name -> nzovu.api.schedule.v1.WeeklyRule
	10, // 13: nzovu.api.schedule.v1.CalendarRule.daily:type_name -> nzovu.api.schedule.v1.DailyRule
	11, // 14: nzovu.api.schedule.v1.CalendarRule.yearly:type_name -> nzovu.api.schedule.v1.YearlyRule
	12, // 15: nzovu.api.schedule.v1.CalendarRule.business_days:type_name -> nzovu.api.schedule.v1.BusinessDaysRule
	13, // 16: nzovu.api.schedule.v1.CalendarRule.custom:type_name -> nzovu.api.schedule.v1.CustomRule
	14, // 17: nzovu.api.schedule.v1.CalendarRule.execution_times:type_name -> nzovu.api.schedule.v1.TimeOfDay
	26, // 18: nzovu.api.schedule.v1.CalendarRule.valid_from:type_name -> google.protobuf.Timestamp
	26, // 19: nzovu.api.schedule.v1.CalendarRule.valid_until:type_name -> google.protobuf.Timestamp
	2,  // 20: nzovu.api.schedule.v1.MonthlyRule.day_type:type_name -> nzovu.api.schedule.v1.MonthlyRule.DayType
	26, // 21: nzovu.api.schedule.v1.WeeklyRule.start_week:type_name -> google.protobuf.Timestamp
	26, // 22: nzovu.api.schedule.v1.DailyRule.start_date:type_name -> google.protobuf.Timestamp
	24, // 23: nzovu.api.schedule.v1.CustomRule.parameters:type_name -> nzovu.api.schedule.v1.CustomRule.ParametersEntry
	16, // 24: nzovu.api.schedule.v1.BusinessCalendar.holidays:type_name -> nzovu.api.schedule.v1.Holiday
	26, // 25: nzovu.api.schedule.v1.Holiday.date:type_name -> google.protobuf.Timestamp
	17, // 26: nzovu.api.schedule.v1.Holiday.rule:type_name -> nzovu.api.schedule.v1.HolidayRule
	18, // 27: nzovu.api.schedule.v1.HolidayRule.fixed:type_name -> nzovu.api.schedule.v1.FixedDate
	19, // 28: nzovu.api.schedule.v1.HolidayRule.relative:type_name -> nzovu.api.schedule.v1.RelativeDate
	20, // 29: nzovu.api.schedule.v1.HolidayRule.easter_offset:type_name -> nzovu.api.schedule.v1.EasterOffset
	26, // 30: nzovu.api.schedule.v1.CalendarException.date:type_name -> google.protobuf.Timestamp
	3,  // 31: nzovu.api.schedule.v1.CalendarException.type:type_name -> nzovu.api.schedule.v1.CalendarException.ExceptionType
	26, // 32: nzovu.api.schedule.v1.CalendarException.reschedule_to:type_name -> google.protobuf.Timestamp
	14, // 33: nzovu.api.schedule.v1.CalendarException.extra_times:type_name -> nzovu.api.schedule.v1.TimeOfDay
	27, // 34: nzovu.api.schedule.v1.Schedule.Metadata.payload:type_name -> nzovu.api.common.v1.Payload
	0,  // 35: nzovu.api.schedule.v1.Schedule.Metadata.state:type_name -> nzovu.api.schedule.v1.Schedule.Metadata.State
	6,  // 36: nzovu.api.schedule.v1.Schedule.Metadata.calendar_schedule:type_name -> nzovu.api.schedule.v1.CalendarSchedule
	26, // 37: nzovu.api.schedule.v1.Schedule.Metadata.next_run:type_name -> google.protobuf.Timestamp
	26, // 38: nzovu.api.schedule.v1.Schedule.Metadata.last_run:type_name -> google.protobuf.Timestamp
	26, // 39: nzovu.api.schedule.v1.Schedule.Metadata.created_at:type_name -> google.protobuf.Timestamp
	26, // 40: nzovu.api.schedule.v1.Schedule.Metadata.updated_at:type_name -> google.protobuf.Timestamp
	28, // 41: nzovu.api.schedule.v1.Schedule.Metadata.lease_duration:type_name -> google.protobuf.Duration
	26, // 42: nzovu.api.schedule.v1.Schedule.Metadata.next_runs:type_name -> google.protobuf.Timestamp
	29, // 43: nzovu.api.schedule.v1.Schedule.Metadata.headers:type_name -> nzovu.api.message.v1.Message.Metadata.Header
	26, // 44: nzovu.api.schedule.v1.ScheduleHistory.Execution.executed_at:type_name -> google.protobuf.Timestamp
	25, // 45: nzovu.api.schedule.v1.ScheduleHistory.Execution.message:type_name -> nzovu.api.message.v1.Message
	46, // [46:46] is the sub-list for method output_type
	46, // [46:46] is the sub-list for method input_type
	46, // [46:46] is the sub-list for extension type_name
	46, // [46:46] is the sub-list for extension extendee
	0,  // [0:46] is the sub-list for field type_name
}

func init() { file_proto_schedule_v1_schedule_proto_init() }
func file_proto_schedule_v1_schedule_proto_init() {
	if File_proto_schedule_v1_schedule_proto != nil {
		return
	}
	file_proto_schedule_v1_schedule_proto_msgTypes[3].OneofWrappers = []any{
		(*CalendarRule_Monthly)(nil),
		(*CalendarRule_Weekly)(nil),
		(*CalendarRule_Daily)(nil),
		(*CalendarRule_Yearly)(nil),
		(*CalendarRule_BusinessDays)(nil),
		(*CalendarRule_Custom)(nil),
	}
	file_proto_schedule_v1_schedule_proto_msgTypes[13].OneofWrappers = []any{
		(*HolidayRule_Fixed)(nil),
		(*HolidayRule_Relative)(nil),
		(*HolidayRule_EasterOffset)(nil),
	}
	file_proto_schedule_v1_schedule_proto_msgTypes[18].OneofWrappers = []any{
		(*Schedule_Metadata_CronSchedule)(nil),
		(*Schedule_Metadata_CalendarSchedule)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_schedule_v1_schedule_proto_rawDesc), len(file_proto_schedule_v1_schedule_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_schedule_v1_schedule_proto_goTypes,
		DependencyIndexes: file_proto_schedule_v1_schedule_proto_depIdxs,
		EnumInfos:         file_proto_schedule_v1_schedule_proto_enumTypes,
		MessageInfos:      file_proto_schedule_v1_schedule_proto_msgTypes,
	}.Build()
	File_proto_schedule_v1_schedule_proto = out.File
	file_proto_schedule_v1_schedule_proto_goTypes = nil
	file_proto_schedule_v1_schedule_proto_depIdxs = nil
}
