# Based on https://github.com/microsoft/vscode-dev-containers/tree/v0.224.3/containers/go/.devcontainer/base.Dockerfile \
# and adapted for Nzovu development

# [Choice] Go version: 1, 1.21, etc
ARG GOVERSION=1.26.6
ARG LINUX_VARIANT=bookworm
FROM golang:${GOVERSION}-${LINUX_VARIANT}

# [Option] Install zsh
ARG INSTALL_ZSH="true"

# [Options] Versions
ARG KUBECTL_VERSION="latest"
ARG HELM_VERSION="latest"
ARG MINIKUBE_VERSION="latest"
ARG PROTOC_VERSION="32.0"
ARG PROTOC_GEN_GO_VERSION="1.36.9"
ARG PROTOC_GEN_GO_GRPC_VERSION="1.5.1"
ARG GOLANGCI_LINT_VERSION="2.5.0"

# This Dockerfile adds a non-root 'nzovu' user with sudo access. However, for Linux,
# this user's GID/UID must match your local user UID/GID to avoid permission issues
# with bind mounts. Update USER_UID / USER_GID if yours is not 1000. See
# https://aka.ms/vscode-remote/containers/non-root-user for details.
ARG USERNAME=nzovu
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Other env vars
ENV GO111MODULE=auto
ENV CGO_ENABLED=0
ENV DOCKER_BUILDKIT=1
ENV DEFAULT_IMAGE_REGISTRY=DOCKER

# Fixing vulnerability issue by upgrading svn to 1.14.5. Ref https://subversion.apache.org/security/CVE-2024-46901-advisory.txt
COPY cve-scripts/install-subversion.sh /tmp/install-subversion.sh
RUN chmod +x /tmp/install-subversion.sh
RUN /tmp/install-subversion.sh \
    && rm -f /tmp/install-subversion.sh

# Setup image using library scripts and configure non-root user.
COPY library-scripts/* custom-scripts/* welcome-notice.txt /tmp/staging/
RUN apt-get update \
    # Install necessary packages
    # Note: ADD_NON_FREE_PACKAGES (7th arg) must be "false" for Bookworm+ which uses DEB822 sources format
    && bash /tmp/staging/common-debian.sh "${INSTALL_ZSH}" "${USERNAME}" "${USER_UID}" "${USER_GID}" "true" "true" "false" \
    # extra custom configurations for non-root user
    && bash /tmp/staging/setup-user.sh "${USERNAME}" "${USERNAME}" "${PATH}" \
    # Install Docker CLI and Engine for Docker-in-Docker
    && bash /tmp/staging/docker-in-docker-debian.sh "true" "${USERNAME}" "false" "latest" \
    # Install kubectl, helm, minikube
    && bash /tmp/staging/kubectl-helm-debian.sh "${KUBECTL_VERSION}" "${HELM_VERSION}" "${MINIKUBE_VERSION}"

# Install Go tools
RUN bash /tmp/staging/go-debian.sh "none" "/usr/local/go" "/go" "${USERNAME}" "false"

# Install Nzovu tools
RUN bash /tmp/staging/install-nzovu-tools.sh "${USERNAME}" "/usr/local/go" "/go" "${PROTOC_VERSION}" "${PROTOC_GEN_GO_VERSION}" "${PROTOC_GEN_GO_GRPC_VERSION}" "${GOLANGCI_LINT_VERSION}"

# Copy init scripts to /usr/local/share
RUN mv -f -t /usr/local/share/ /tmp/staging/docker-bind-mount.sh /tmp/staging/devcontainer-init.sh /tmp/staging/setup-docker-multiarch.sh \
    && chmod +x /usr/local/share/docker-bind-mount.sh /usr/local/share/devcontainer-init.sh  /usr/local/share/setup-docker-multiarch.sh \
    && chown ${USERNAME}:root /usr/local/share/docker-bind-mount.sh /usr/local/share/devcontainer-init.sh  /usr/local/share/setup-docker-multiarch.sh

# Move the welcome notice to workspace location
RUN mkdir -p /usr/local/etc/vscode-dev-containers/ \
    && mv -f /tmp/staging/welcome-notice.txt /usr/local/etc/vscode-dev-containers/ \
    #
    # Set permissions of workspace
    && mkdir -p /workspaces && chown ${USERNAME} /workspaces \
    #
    # Clean up packages and the staging folder.
    && apt-get autoremove -y && apt-get clean -y && rm -rf /tmp/staging

# Mount for docker-in-docker
VOLUME [ "/var/lib/docker" ]

# Initialize Nzovu devcontainer script
ENTRYPOINT [ "/usr/local/share/devcontainer-init.sh" ]
CMD [ "sleep", "infinity" ]

USER ${USERNAME}
