// ChronoQueue Service API v1
//
// This file defines the complete gRPC service interface for ChronoQueue.
// All client operations go through this service.
//
// Service categories:
// 1. Queue Management: Create, delete, list, get state
// 2. Message Operations: Post, get, acknowledge, renew lease, peek, heartbeat
// 3. Schedule Management: Create, delete, get, list, pause, resume, history
// 4. Dead Letter Queue: Get messages, requeue, delete, purge, stats
// 5. Calendar Schedules: Validate, preview
// 6. Schema Management: Register, get, list, delete, validate payloads
//
// All RPCs support both gRPC and REST (via gRPC-Gateway annotations).
// REST endpoints follow Google API Design Guide conventions.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: proto/queueservice/v1/service.proto

package queueservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QueueService_CreateQueue_FullMethodName              = "/nzovu.api.queueservice.v1.QueueService/CreateQueue"
	QueueService_DeleteQueue_FullMethodName              = "/nzovu.api.queueservice.v1.QueueService/DeleteQueue"
	QueueService_ListQueues_FullMethodName               = "/nzovu.api.queueservice.v1.QueueService/ListQueues"
	QueueService_GetQueueState_FullMethodName            = "/nzovu.api.queueservice.v1.QueueService/GetQueueState"
	QueueService_PostMessage_FullMethodName              = "/nzovu.api.queueservice.v1.QueueService/PostMessage"
	QueueService_PostMessagesBulk_FullMethodName         = "/nzovu.api.queueservice.v1.QueueService/PostMessagesBulk"
	QueueService_GetNextMessage_FullMethodName           = "/nzovu.api.queueservice.v1.QueueService/GetNextMessage"
	QueueService_AcknowledgeMessage_FullMethodName       = "/nzovu.api.queueservice.v1.QueueService/AcknowledgeMessage"
	QueueService_CancelMessage_FullMethodName            = "/nzovu.api.queueservice.v1.QueueService/CancelMessage"
	QueueService_RenewMessageLease_FullMethodName        = "/nzovu.api.queueservice.v1.QueueService/RenewMessageLease"
	QueueService_PeekQueueMessages_FullMethodName        = "/nzovu.api.queueservice.v1.QueueService/PeekQueueMessages"
	QueueService_SendMessageHeartBeat_FullMethodName     = "/nzovu.api.queueservice.v1.QueueService/SendMessageHeartBeat"
	QueueService_CreateSchedule_FullMethodName           = "/nzovu.api.queueservice.v1.QueueService/CreateSchedule"
	QueueService_DeleteSchedule_FullMethodName           = "/nzovu.api.queueservice.v1.QueueService/DeleteSchedule"
	QueueService_GetSchedule_FullMethodName              = "/nzovu.api.queueservice.v1.QueueService/GetSchedule"
	QueueService_ListSchedules_FullMethodName            = "/nzovu.api.queueservice.v1.QueueService/ListSchedules"
	QueueService_GetScheduleHistory_FullMethodName       = "/nzovu.api.queueservice.v1.QueueService/GetScheduleHistory"
	QueueService_PauseSchedule_FullMethodName            = "/nzovu.api.queueservice.v1.QueueService/PauseSchedule"
	QueueService_ResumeSchedule_FullMethodName           = "/nzovu.api.queueservice.v1.QueueService/ResumeSchedule"
	QueueService_GetDLQMessages_FullMethodName           = "/nzovu.api.queueservice.v1.QueueService/GetDLQMessages"
	QueueService_RequeueFromDLQ_FullMethodName           = "/nzovu.api.queueservice.v1.QueueService/RequeueFromDLQ"
	QueueService_DeleteFromDLQ_FullMethodName            = "/nzovu.api.queueservice.v1.QueueService/DeleteFromDLQ"
	QueueService_PurgeDLQ_FullMethodName                 = "/nzovu.api.queueservice.v1.QueueService/PurgeDLQ"
	QueueService_GetDLQStats_FullMethodName              = "/nzovu.api.queueservice.v1.QueueService/GetDLQStats"
	QueueService_ValidateCalendarSchedule_FullMethodName = "/nzovu.api.queueservice.v1.QueueService/ValidateCalendarSchedule"
	QueueService_PreviewCalendarSchedule_FullMethodName  = "/nzovu.api.queueservice.v1.QueueService/PreviewCalendarSchedule"
	QueueService_RegisterSchema_FullMethodName           = "/nzovu.api.queueservice.v1.QueueService/RegisterSchema"
	QueueService_GetSchema_FullMethodName                = "/nzovu.api.queueservice.v1.QueueService/GetSchema"
	QueueService_ListSchemas_FullMethodName              = "/nzovu.api.queueservice.v1.QueueService/ListSchemas"
	QueueService_DeleteSchema_FullMethodName             = "/nzovu.api.queueservice.v1.QueueService/DeleteSchema"
	QueueService_ValidatePayload_FullMethodName          = "/nzovu.api.queueservice.v1.QueueService/ValidatePayload"
)

// QueueServiceClient is the client API for QueueService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// QueueService is the primary API for interacting with ChronoQueue.
//
// This service provides:
// - Queue lifecycle management
// - Message posting and consumption
// - Scheduled task automation
// - Dead letter queue handling
// - Schema-based validation
//
// Example - Basic message flow:
//  1. CreateQueue: Set up a queue with retry/DLQ configuration
//  2. PostMessage: Add messages to the queue
//  3. GetNextMessage: Workers retrieve messages for processing
//  4. AcknowledgeMessage: Mark message as successfully processed
//     OR let lease expire → message returns to queue for retry
//  5. After max_attempts exhausted → message moves to DLQ
//
// gRPC vs REST:
// - gRPC: Preferred for high-throughput, low-latency scenarios
// - REST: Convenient for browser/curl access, debugging, simple integrations
//
// Error handling:
// - Use gRPC status codes (InvalidArgument, NotFound, AlreadyExists, etc.)
// - Error details in status.Details() for validation errors
type QueueServiceClient interface {
	// CreateQueue creates a new queue with specified configuration.
	//
	// Use to:
	// - Define retry behavior (max_attempts, lease_duration)
	// - Set up dead letter queue for failed messages
	// - Configure priority handling
	// - Enforce message schemas
	//
	// Example:
	//
	//	POST /v1/queues
	//	{
	//	  "name": "order-processing",
	//	  "metadata": {
	//	    "default_max_attempts": 3,
	//	    "lease_duration": "300s",
	//	    "auto_create_dlq": true
	//	  }
	//	}
	//
	// Returns: success status
	// Errors:
	//   - AlreadyExists: Queue with this name exists
	//   - InvalidArgument: Invalid configuration (negative lease_duration, etc.)
	CreateQueue(ctx context.Context, in *CreateQueueRequest, opts ...grpc.CallOption) (*CreateQueueResponse, error)
	// DeleteQueue permanently deletes a queue and all its messages.
	//
	// WARNING: This operation is irreversible. All pending and running messages are lost.
	//
	// Use when:
	// - Decommissioning a feature
	// - Cleaning up test queues
	// - Removing unused queues
	//
	// Best practice: Drain queue first (stop posting, wait for workers to finish).
	//
	// Example:
	//
	//	DELETE /v1/queues/order-processing
	//
	// Returns: success status
	// Errors:
	//   - NotFound: Queue doesn't exist
	DeleteQueue(ctx context.Context, in *DeleteQueueRequest, opts ...grpc.CallOption) (*DeleteQueueResponse, error)
	// ListQueues returns all queues in your ChronoQueue instance.
	//
	// Use for:
	// - Monitoring dashboards
	// - Queue discovery
	// - Debugging
	//
	// Example:
	//
	//	GET /v1/queues
	//
	// Returns: List of Queue objects with metadata
	ListQueues(ctx context.Context, in *ListQueuesRequest, opts ...grpc.CallOption) (*ListQueuesResponse, error)
	// GetQueueState returns current queue statistics and health.
	//
	// Provides:
	// - Message counts by state (INVISIBLE, PENDING, RUNNING, COMPLETED, CANCELED, ERRORED)
	// - Earliest active lease or heartbeat deadline
	//
	// Use for:
	// - Health checks
	// - Autoscaling decisions (scale workers based on PENDING count)
	// - Alerting (high ERRORED count, DLQ growth)
	//
	// Example:
	//
	//	GET /v1/queues/order-processing/state
	//	Response:
	//	{
	//	  "stateCounts": {"INVISIBLE": "0", "PENDING": "150", "RUNNING": "10", "COMPLETED": "5420", "CANCELED": "0", "ERRORED": "3"}
	//	}
	//
	// Returns: state counts and the earliest active deadline
	GetQueueState(ctx context.Context, in *GetQueueStateRequest, opts ...grpc.CallOption) (*GetQueueStateResponse, error)
	// PostMessage adds a new message to a queue.
	//
	// Use for:
	// - Asynchronous task execution
	// - Event-driven workflows
	// - Job scheduling
	// - Load leveling
	//
	// Features:
	// - Delayed execution (scheduled_time)
	// - Priority ordering
	// - Schema validation
	// - Deduplication by message_id within the queue
	// - Exclusive processing (exclusivity_key)
	//
	// Example - immediate execution:
	//
	//	POST /v1/queues/order-processing/messages
	//	{
	//	  "message": {
	//	    "messageId": "order-123",
	//	    "metadata": {
	//	      "payload": {"data": "..."},
	//	      "priority": 4
	//	    }
	//	  }
	//	}
	//
	// Example - delayed execution (send email in 1 hour):
	//
	//	{
	//	  "message": {
	//	    "messageId": "email-123",
	//	    "metadata": {
	//	      "payload": {"data": "..."},
	//	      "scheduledTime": "2024-12-01T15:00:00Z"
	//	    }
	//	  }
	//	}
	//
	// The caller must provide messageId. Returns success status.
	// Errors:
	//   - NotFound: Queue doesn't exist
	//   - InvalidArgument: Schema validation failed, invalid scheduled_time
	//   - AlreadyExists: Duplicate message_id in the queue
	PostMessage(ctx context.Context, in *PostMessageRequest, opts ...grpc.CallOption) (*PostMessageResponse, error)
	// PostMessagesBulk posts multiple messages to a queue in a single operation.
	//
	// Supports two transaction modes:
	//   - ALL_OR_NOTHING: All messages succeed or all fail (atomic)
	//   - BEST_EFFORT: Independent processing, partial success allowed
	//
	// Limits:
	//   - Max 1000 messages per request
	//   - Max 1MB total payload size
	//
	// Errors:
	//   - NotFound: Queue doesn't exist
	//   - InvalidArgument: Too many messages, payload too large, invalid mode
	//   - FailedPrecondition: One or more messages failed in ALL_OR_NOTHING mode (entire batch rejected)
	//
	// Individual message errors are returned in the response with per-message error codes.
	PostMessagesBulk(ctx context.Context, in *PostMessagesBulkRequest, opts ...grpc.CallOption) (*PostMessagesBulkResponse, error)
	// GetNextMessage retrieves the next available message for processing.
	//
	// This is the primary worker API. Call in a loop to continuously process messages.
	//
	// Behavior:
	// - Returns highest priority PENDING message
	// - Message moves to RUNNING state
	// - Lease timer starts (worker has lease_duration to process)
	// - If lease expires without ACK → message returns to PENDING for retry
	//
	// Concurrency:
	//   - Multiple workers can call simultaneously
	//   - Each worker gets a different message (no duplicates)
	//   - EXCLUSIVE queues require their configured exclusivity_key and allow one
	//     RUNNING message until it is acknowledged, failed, or reclaimed
	//
	// Example worker loop:
	//
	//	for {
	//	    resp := client.GetNextMessage(ctx, &GetNextMessageRequest{
	//	        QueueName: "order-processing",
	//	        LeaseDuration: durationpb.New(5 * time.Minute),
	//	    })
	//	    if resp.Message == nil {
	//	        time.Sleep(1 * time.Second)  // No messages available
	//	        continue
	//	    }
	//
	//	    err := processMessage(resp.Message)
	//	    if err != nil {
	//	        // Let lease expire → automatic retry
	//	        continue
	//	    }
	//
	//	    client.AcknowledgeMessage(ctx, &AcknowledgeMessageRequest{
	//	        QueueName: "order-processing",
	//	        MessageId: resp.Message.MessageId,
	//	    })
	//	}
	//
	// Returns: Message (or empty if no messages available)
	// Errors:
	//   - NotFound: Queue doesn't exist
	GetNextMessage(ctx context.Context, in *GetNextMessageRequest, opts ...grpc.CallOption) (*GetNextMessageResponse, error)
	// AcknowledgeMessage marks a message as successfully processed.
	//
	// Call this after successfully processing a message retrieved by GetNextMessage.
	//
	// Effects:
	// - Message moves to COMPLETED state
	// - Message retained or removed according to the queue retention policy
	// - Queue stats updated
	//
	// Important: attempt_id and worker_id from GetNextMessage are required and
	// must identify the active, unexpired lease.
	//
	// Example:
	//
	//	POST /v1/queues/order-processing/messages/msg-123:acknowledge
	//
	// Returns: success status
	// Errors:
	//   - NotFound: Message doesn't exist or already acknowledged
	//   - DeadlineExceeded: Lease already expired
	AcknowledgeMessage(ctx context.Context, in *AcknowledgeMessageRequest, opts ...grpc.CallOption) (*AcknowledgeMessageResponse, error)
	// CancelMessage cancels a pending message before it has been processed.
	//
	// Use when:
	// - Business logic invalidates the need for a message (order cancelled, user unsubscribed)
	// - Scheduled messages no longer needed (event rescheduled, task no longer relevant)
	// - Cleanup operations (purge old scheduled notifications)
	//
	// Producer-side operation: Only messages in INVISIBLE or PENDING state can be cancelled.
	// Messages already being processed (RUNNING) cannot be cancelled - use application-level
	// cancellation logic instead.
	//
	// Effects:
	// - Message moves to CANCELED state
	// - Message removed from processing queue
	// - Message retained based on retention policy (soft delete)
	// - Queue stats updated
	//
	// Example - cancel scheduled reminder:
	//
	//	POST /v1/queues/notifications/messages/reminder-456:cancel
	//
	// Example - cancel all pending messages for a user:
	//
	//	foreach messageId in userMessages:
	//	    CancelMessage(queueName, messageId)
	//
	// Returns: success status
	// Errors:
	//   - NotFound: Message doesn't exist
	//   - FailedPrecondition: Message is RUNNING, COMPLETED, ERRORED, or already CANCELED
	CancelMessage(ctx context.Context, in *CancelMessageRequest, opts ...grpc.CallOption) (*CancelMessageResponse, error)
	// RenewMessageLease extends the processing time for a message.
	//
	// Use when:
	// - Processing takes longer than expected
	// - Long-running batch operations
	// - External API calls with unpredictable latency
	//
	// Call periodically during processing to prevent lease expiration.
	// attempt_id and worker_id from GetNextMessage are required and must identify
	// the active, unexpired lease.
	// An omitted lease_duration uses the queue/message extend_step. Renewal fails
	// without consuming a renewal when no positive extension remains.
	//
	// Example pattern (heartbeat-style lease renewal):
	//
	//	msg := getNextMessage()
	//	done := make(chan bool)
	//
	//	go func() {
	//	    ticker := time.NewTicker(leaseDuration / 2)
	//	    defer ticker.Stop()
	//	    for {
	//	        select {
	//	        case <-ticker.C:
	//	            renewMessageLease(msg.MessageId)
	//	        case <-done:
	//	            return
	//	        }
	//	    }
	//	}()
	//
	//	processMessage(msg)
	//	close(done)
	//	acknowledgeMessage(msg.MessageId)
	//
	// Returns: remaining lease time and current state
	// Errors:
	//   - NotFound: Message doesn't exist or already completed
	//   - FailedPrecondition: Message not in RUNNING state
	RenewMessageLease(ctx context.Context, in *RenewMessageLeaseRequest, opts ...grpc.CallOption) (*RenewMessageLeaseResponse, error)
	// PeekQueueMessages views messages without leasing them.
	//
	// Use for:
	// - Debugging (inspect message payloads)
	// - Monitoring (see what's pending)
	// - Admin dashboards
	//
	// Does NOT:
	// - Change message state
	// - Create leases
	// - Affect message ordering
	//
	// Example:
	//
	//	GET /v1/queues/order-processing/messages:peek?page_size=10
	//
	// Returns: One deterministically ordered page of pending messages.
	PeekQueueMessages(ctx context.Context, in *PeekQueueMessagesRequest, opts ...grpc.CallOption) (*PeekQueueMessagesResponse, error)
	// SendMessageHeartBeat indicates a worker is still processing a message.
	//
	// Alternative to RenewMessageLease that records worker liveness and extends
	// the lease to the configured heartbeat timeout.
	// attempt_id and worker_id from GetNextMessage are required and must identify
	// the active, unexpired lease.
	//
	// Example:
	//
	//	POST /v1/queues/order-processing/messages:heartbeat
	//	{
	//	  "messageId": "msg-123",
	//	  "attemptId": "attempt-123",
	//	  "workerId": "worker-1"
	//	}
	//
	// Returns: remaining lease time and current state
	SendMessageHeartBeat(ctx context.Context, in *SendMessageHeartBeatRequest, opts ...grpc.CallOption) (*SendMessageHeartBeatResponse, error)
	// CreateSchedule creates a recurring message posting schedule.
	//
	// Use for:
	// - Cron-style job scheduling (daily reports, hourly cleanup)
	// - Business calendar scheduling (first business day of month)
	// - Recurring notifications (reminders, alerts)
	// - Periodic batch processing
	//
	// Supports:
	// - Simple cron expressions: "0 9 * * 1-5" (weekdays at 9 AM)
	// - Complex calendar rules: "last Friday of each quarter"
	// - Timezone-aware scheduling
	// - Holiday handling
	//
	// Example - daily report at 8 AM EST:
	//
	//	POST /v1/schedules
	//	{
	//	  "schedule": {
	//	    "schedule_id": "daily-sales-report",
	//	    "metadata": {
	//	      "cron_schedule": "0 8 * * *",
	//	      "timezone": "America/New_York",
	//	      "queue_name": "reports",
	//	      "payload": {...}
	//	    }
	//	  }
	//	}
	//
	// Returns: success status
	// Errors:
	//   - AlreadyExists: schedule_id already in use
	//   - InvalidArgument: Invalid cron expression or calendar rule
	CreateSchedule(ctx context.Context, in *CreateScheduleRequest, opts ...grpc.CallOption) (*CreateScheduleResponse, error)
	// DeleteSchedule permanently removes a schedule.
	//
	// Effects:
	// - Schedule stops creating new messages
	// - Existing messages already posted remain in queue
	// - Schedule history is preserved
	//
	// Example:
	//
	//	DELETE /v1/schedules/daily-sales-report
	//
	// Returns: success status
	// Errors:
	//   - NotFound: Schedule doesn't exist
	DeleteSchedule(ctx context.Context, in *DeleteScheduleRequest, opts ...grpc.CallOption) (*DeleteScheduleResponse, error)
	// GetSchedule retrieves schedule details and current state.
	//
	// Returns:
	// - Schedule configuration
	// - Current state (SCHEDULED, PAUSED, CANCELED, ERRORED)
	// - Next execution time
	// - Last execution time
	// - Execution count
	//
	// Example:
	//
	//	GET /v1/schedules/daily-sales-report
	//
	// Returns: Schedule object
	// Errors:
	//   - NotFound: Schedule doesn't exist
	GetSchedule(ctx context.Context, in *GetScheduleRequest, opts ...grpc.CallOption) (*GetScheduleResponse, error)
	// ListSchedules returns all schedules.
	//
	// Use for:
	// - Admin dashboards
	// - Monitoring active schedules
	// - Discovering schedules
	//
	// Example:
	//
	//	GET /v1/schedules
	//
	// Returns: List of Schedule objects
	ListSchedules(ctx context.Context, in *ListSchedulesRequest, opts ...grpc.CallOption) (*ListSchedulesResponse, error)
	// GetScheduleHistory returns execution history for a schedule.
	//
	// Shows:
	// - Past executions with timestamps
	// - Messages created by each execution
	// - Success/failure status
	//
	// Use for:
	// - Debugging missed executions
	// - Auditing schedule activity
	// - Verifying schedule correctness
	//
	// Example:
	//
	//	GET /v1/schedules/daily-sales-report/history
	//
	// Returns: ScheduleHistory with execution records
	GetScheduleHistory(ctx context.Context, in *GetScheduleHistoryRequest, opts ...grpc.CallOption) (*GetScheduleHistoryResponse, error)
	// PauseSchedule temporarily stops a schedule from creating messages.
	//
	// Use when:
	// - Temporarily disabling a feature
	// - During maintenance windows
	// - Debugging issues
	//
	// Effects:
	// - Schedule state → PAUSED
	// - No new messages created
	// - Can be resumed later with ResumeSchedule
	//
	// Example:
	//
	//	POST /v1/schedules/daily-sales-report:pause
	//
	// Returns: success status
	// Errors:
	//   - NotFound: Schedule doesn't exist
	//   - FailedPrecondition: Schedule not in SCHEDULED state
	PauseSchedule(ctx context.Context, in *PauseScheduleRequest, opts ...grpc.CallOption) (*PauseScheduleResponse, error)
	// ResumeSchedule reactivates a paused schedule.
	//
	// Effects:
	// - Schedule state → SCHEDULED
	// - Resets the max_messages execution counter
	// - Retains next_run; an overdue run is eligible immediately after resume
	// - Does NOT backfill missed executions during pause
	//
	// Example:
	//
	//	POST /v1/schedules/daily-sales-report:resume
	//
	// Returns: success status
	// Errors:
	//   - NotFound: Schedule doesn't exist
	//   - FailedPrecondition: Schedule not in PAUSED state
	ResumeSchedule(ctx context.Context, in *ResumeScheduleRequest, opts ...grpc.CallOption) (*ResumeScheduleResponse, error)
	// GetDLQMessages retrieves messages from a dead letter queue.
	//
	// Dead letter queues contain:
	// - Messages that exhausted retry attempts
	// - Messages that caused persistent errors
	// - Messages rejected by workers
	//
	// Use for:
	// - Investigating failures
	// - Manual reprocessing after fixing bugs
	// - Identifying systematic issues
	//
	// Example:
	//
	//	GET /v1/dlq/order-dlq/messages?page_size=50
	//
	// Returns: List of failed messages with error details
	GetDLQMessages(ctx context.Context, in *GetDLQMessagesRequest, opts ...grpc.CallOption) (*GetDLQMessagesResponse, error)
	// RequeueFromDLQ moves a message from DLQ to the required target queue.
	//
	// Use after:
	// - Fixing bugs that caused failures
	// - Resolving external service outages
	// - Correcting data issues
	//
	// Effects:
	// - Message removed from DLQ
	// - Message added to targetQueue as PENDING
	// - attempts_left always reset
	//
	// Example:
	//
	//	POST /v1/dlq/order-dlq/messages/msg-123:requeue
	//	{
	//	  "targetQueue": "orders"
	//	}
	//
	// Returns: success status
	// Errors:
	//   - NotFound: Message not in DLQ
	//   - NotFound: Target queue does not exist
	//   - InvalidArgument: targetQueue is empty
	RequeueFromDLQ(ctx context.Context, in *RequeueFromDLQRequest, opts ...grpc.CallOption) (*RequeueFromDLQResponse, error)
	// DeleteFromDLQ permanently removes a message from the DLQ.
	//
	// Use when:
	// - Message is not recoverable
	// - Data is no longer relevant
	// - Cleaning up test data
	//
	// WARNING: This is permanent. Message cannot be recovered.
	//
	// Example:
	//
	//	DELETE /v1/dlq/order-dlq/messages/msg-123
	//
	// Returns: success status
	// Errors:
	//   - NotFound: Message not in DLQ
	DeleteFromDLQ(ctx context.Context, in *DeleteFromDLQRequest, opts ...grpc.CallOption) (*DeleteFromDLQResponse, error)
	// PurgeDLQ removes all messages from a dead letter queue.
	//
	// Use when:
	// - Cleaning up after incident
	// - Clearing test data
	// - DLQ too large to manage individually
	//
	// WARNING: This is irreversible. All DLQ messages are permanently deleted.
	//
	// Example:
	//
	//	POST /v1/dlq/order-dlq:purge
	//
	// Returns: Whether the purge succeeded
	PurgeDLQ(ctx context.Context, in *PurgeDLQRequest, opts ...grpc.CallOption) (*PurgeDLQResponse, error)
	// GetDLQStats returns statistics about a dead letter queue.
	//
	// Provides:
	// - Message count
	// - Queue creation and update timestamps
	//
	// Use for:
	// - Monitoring DLQ health
	// - Alerting on DLQ growth
	// - Identifying systemic issues
	//
	// Example:
	//
	//	GET /v1/dlq/order-dlq/stats
	//
	// Returns: DLQ statistics
	GetDLQStats(ctx context.Context, in *GetDLQStatsRequest, opts ...grpc.CallOption) (*GetDLQStatsResponse, error)
	// ValidateCalendarSchedule checks if a calendar schedule is valid.
	//
	// Validates:
	// - Calendar rule correctness
	// - Timezone validity
	// - Holiday rule logic
	//
	// Use before CreateSchedule to catch configuration errors.
	//
	// Example:
	//
	//	POST /v1/calendar-schedules:validate
	//	{
	//	  "calendar_schedule": {...}
	//	}
	//
	// Returns: Validation result with errors if invalid
	ValidateCalendarSchedule(ctx context.Context, in *ValidateCalendarScheduleRequest, opts ...grpc.CallOption) (*ValidateCalendarScheduleResponse, error)
	// PreviewCalendarSchedule shows next N execution times for a schedule.
	//
	// Use to:
	// - Verify schedule behaves as expected
	// - Test complex calendar rules
	// - Confirm timezone handling
	// - Preview holiday exceptions
	//
	// Example:
	//
	//	POST /v1/calendar-schedules:preview
	//	{
	//	  "calendar_schedule": {...},
	//	  "count": 10  // Next 10 executions
	//	}
	//
	//	Response:
	//	{
	//	  "next_runs": [
	//	    "2024-01-02T09:00:00Z",
	//	    "2024-01-03T09:00:00Z",
	//	    "2024-01-04T09:00:00Z",
	//	    ...
	//	  ]
	//	}
	//
	// Returns: List of upcoming execution timestamps
	PreviewCalendarSchedule(ctx context.Context, in *PreviewCalendarScheduleRequest, opts ...grpc.CallOption) (*PreviewCalendarScheduleResponse, error)
	// RegisterSchema creates the next version of a message validation schema.
	//
	// Use for:
	// - Enforcing message structure
	// - API contract validation
	// - Data quality checks
	// - Type safety
	//
	// Schema versioning:
	// - Each schema has a schema_id and a server-assigned version number
	// - Multiple versions can coexist
	// - Queues reference schema_id (use highest active version)
	//
	// Example:
	//
	//	POST /v1/schemas
	//	{
	//	  "schema_id": "order-schema",
	//	  "name": "Order schema",
	//	  "content": "{...JSON Schema...}",
	//	  "content_type": "json-schema"
	//	}
	//
	// Returns: Registered schema
	// Errors:
	//   - InvalidArgument: Invalid schema syntax
	RegisterSchema(ctx context.Context, in *RegisterSchemaRequest, opts ...grpc.CallOption) (*RegisterSchemaResponse, error)
	// GetSchema retrieves a specific schema version.
	//
	// Example:
	//
	//	GET /v1/schemas/order-schema/versions/2
	//
	// Returns: Schema details
	// Errors:
	//   - NotFound: Schema not found
	GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*GetSchemaResponse, error)
	// ListSchemas returns one summary for each registered schema family.
	//
	// Use for:
	// - Schema discovery
	// - Admin dashboards
	// - Schema management
	//
	// Example:
	//
	//	GET /v1/schemas
	//
	// Returns: Latest matching version and aggregate version metadata for each family
	ListSchemas(ctx context.Context, in *ListSchemasRequest, opts ...grpc.CallOption) (*ListSchemasResponse, error)
	// DeleteSchema deactivates a schema version, or all versions when version is 0.
	//
	// Effects:
	// - Matching active schema versions are marked inactive
	// - Inactive versions remain addressable for validation history
	//
	// Example:
	//
	//	DELETE /v1/schemas/order-schema/versions/1
	//
	// Returns: Number of versions deactivated
	// Errors:
	//   - NotFound: Schema not found
	DeleteSchema(ctx context.Context, in *DeleteSchemaRequest, opts ...grpc.CallOption) (*DeleteSchemaResponse, error)
	// ValidatePayload validates a payload against a schema without posting a message.
	//
	// Use for:
	// - Pre-flight validation
	// - Testing schema changes
	// - Client-side validation
	// - Development/debugging
	//
	// Example:
	//
	//	POST /v1/schemas/order-schema/versions/2:validate
	//	{
	//	  "payload": {
	//	    "data": "{\"orderId\": \"ORD-123\", ...}"
	//	  }
	//	}
	//
	// Returns: ValidationResult (valid=true or list of errors)
	ValidatePayload(ctx context.Context, in *ValidatePayloadRequest, opts ...grpc.CallOption) (*ValidatePayloadResponse, error)
}

type queueServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQueueServiceClient(cc grpc.ClientConnInterface) QueueServiceClient {
	return &queueServiceClient{cc}
}

func (c *queueServiceClient) CreateQueue(ctx context.Context, in *CreateQueueRequest, opts ...grpc.CallOption) (*CreateQueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateQueueResponse)
	err := c.cc.Invoke(ctx, QueueService_CreateQueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) DeleteQueue(ctx context.Context, in *DeleteQueueRequest, opts ...grpc.CallOption) (*DeleteQueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteQueueResponse)
	err := c.cc.Invoke(ctx, QueueService_DeleteQueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) ListQueues(ctx context.Context, in *ListQueuesRequest, opts ...grpc.CallOption) (*ListQueuesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListQueuesResponse)
	err := c.cc.Invoke(ctx, QueueService_ListQueues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) GetQueueState(ctx context.Context, in *GetQueueStateRequest, opts ...grpc.CallOption) (*GetQueueStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQueueStateResponse)
	err := c.cc.Invoke(ctx, QueueService_GetQueueState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) PostMessage(ctx context.Context, in *PostMessageRequest, opts ...grpc.CallOption) (*PostMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostMessageResponse)
	err := c.cc.Invoke(ctx, QueueService_PostMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) PostMessagesBulk(ctx context.Context, in *PostMessagesBulkRequest, opts ...grpc.CallOption) (*PostMessagesBulkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostMessagesBulkResponse)
	err := c.cc.Invoke(ctx, QueueService_PostMessagesBulk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) GetNextMessage(ctx context.Context, in *GetNextMessageRequest, opts ...grpc.CallOption) (*GetNextMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNextMessageResponse)
	err := c.cc.Invoke(ctx, QueueService_GetNextMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) AcknowledgeMessage(ctx context.Context, in *AcknowledgeMessageRequest, opts ...grpc.CallOption) (*AcknowledgeMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcknowledgeMessageResponse)
	err := c.cc.Invoke(ctx, QueueService_AcknowledgeMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) CancelMessage(ctx context.Context, in *CancelMessageRequest, opts ...grpc.CallOption) (*CancelMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelMessageResponse)
	err := c.cc.Invoke(ctx, QueueService_CancelMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) RenewMessageLease(ctx context.Context, in *RenewMessageLeaseRequest, opts ...grpc.CallOption) (*RenewMessageLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewMessageLeaseResponse)
	err := c.cc.Invoke(ctx, QueueService_RenewMessageLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) PeekQueueMessages(ctx context.Context, in *PeekQueueMessagesRequest, opts ...grpc.CallOption) (*PeekQueueMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeekQueueMessagesResponse)
	err := c.cc.Invoke(ctx, QueueService_PeekQueueMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) SendMessageHeartBeat(ctx context.Context, in *SendMessageHeartBeatRequest, opts ...grpc.CallOption) (*SendMessageHeartBeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageHeartBeatResponse)
	err := c.cc.Invoke(ctx, QueueService_SendMessageHeartBeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) CreateSchedule(ctx context.Context, in *CreateScheduleRequest, opts ...grpc.CallOption) (*CreateScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateScheduleResponse)
	err := c.cc.Invoke(ctx, QueueService_CreateSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) DeleteSchedule(ctx context.Context, in *DeleteScheduleRequest, opts ...grpc.CallOption) (*DeleteScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteScheduleResponse)
	err := c.cc.Invoke(ctx, QueueService_DeleteSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) GetSchedule(ctx context.Context, in *GetScheduleRequest, opts ...grpc.CallOption) (*GetScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetScheduleResponse)
	err := c.cc.Invoke(ctx, QueueService_GetSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) ListSchedules(ctx context.Context, in *ListSchedulesRequest, opts ...grpc.CallOption) (*ListSchedulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSchedulesResponse)
	err := c.cc.Invoke(ctx, QueueService_ListSchedules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) GetScheduleHistory(ctx context.Context, in *GetScheduleHistoryRequest, opts ...grpc.CallOption) (*GetScheduleHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetScheduleHistoryResponse)
	err := c.cc.Invoke(ctx, QueueService_GetScheduleHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) PauseSchedule(ctx context.Context, in *PauseScheduleRequest, opts ...grpc.CallOption) (*PauseScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PauseScheduleResponse)
	err := c.cc.Invoke(ctx, QueueService_PauseSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) ResumeSchedule(ctx context.Context, in *ResumeScheduleRequest, opts ...grpc.CallOption) (*ResumeScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeScheduleResponse)
	err := c.cc.Invoke(ctx, QueueService_ResumeSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) GetDLQMessages(ctx context.Context, in *GetDLQMessagesRequest, opts ...grpc.CallOption) (*GetDLQMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDLQMessagesResponse)
	err := c.cc.Invoke(ctx, QueueService_GetDLQMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) RequeueFromDLQ(ctx context.Context, in *RequeueFromDLQRequest, opts ...grpc.CallOption) (*RequeueFromDLQResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequeueFromDLQResponse)
	err := c.cc.Invoke(ctx, QueueService_RequeueFromDLQ_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) DeleteFromDLQ(ctx context.Context, in *DeleteFromDLQRequest, opts ...grpc.CallOption) (*DeleteFromDLQResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFromDLQResponse)
	err := c.cc.Invoke(ctx, QueueService_DeleteFromDLQ_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) PurgeDLQ(ctx context.Context, in *PurgeDLQRequest, opts ...grpc.CallOption) (*PurgeDLQResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PurgeDLQResponse)
	err := c.cc.Invoke(ctx, QueueService_PurgeDLQ_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) GetDLQStats(ctx context.Context, in *GetDLQStatsRequest, opts ...grpc.CallOption) (*GetDLQStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDLQStatsResponse)
	err := c.cc.Invoke(ctx, QueueService_GetDLQStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) ValidateCalendarSchedule(ctx context.Context, in *ValidateCalendarScheduleRequest, opts ...grpc.CallOption) (*ValidateCalendarScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateCalendarScheduleResponse)
	err := c.cc.Invoke(ctx, QueueService_ValidateCalendarSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) PreviewCalendarSchedule(ctx context.Context, in *PreviewCalendarScheduleRequest, opts ...grpc.CallOption) (*PreviewCalendarScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreviewCalendarScheduleResponse)
	err := c.cc.Invoke(ctx, QueueService_PreviewCalendarSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) RegisterSchema(ctx context.Context, in *RegisterSchemaRequest, opts ...grpc.CallOption) (*RegisterSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterSchemaResponse)
	err := c.cc.Invoke(ctx, QueueService_RegisterSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*GetSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSchemaResponse)
	err := c.cc.Invoke(ctx, QueueService_GetSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) ListSchemas(ctx context.Context, in *ListSchemasRequest, opts ...grpc.CallOption) (*ListSchemasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSchemasResponse)
	err := c.cc.Invoke(ctx, QueueService_ListSchemas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) DeleteSchema(ctx context.Context, in *DeleteSchemaRequest, opts ...grpc.CallOption) (*DeleteSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSchemaResponse)
	err := c.cc.Invoke(ctx, QueueService_DeleteSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) ValidatePayload(ctx context.Context, in *ValidatePayloadRequest, opts ...grpc.CallOption) (*ValidatePayloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidatePayloadResponse)
	err := c.cc.Invoke(ctx, QueueService_ValidatePayload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueueServiceServer is the server API for QueueService service.
// All implementations should embed UnimplementedQueueServiceServer
// for forward compatibility.
//
// QueueService is the primary API for interacting with ChronoQueue.
//
// This service provides:
// - Queue lifecycle management
// - Message posting and consumption
// - Scheduled task automation
// - Dead letter queue handling
// - Schema-based validation
//
// Example - Basic message flow:
//  1. CreateQueue: Set up a queue with retry/DLQ configuration
//  2. PostMessage: Add messages to the queue
//  3. GetNextMessage: Workers retrieve messages for processing
//  4. AcknowledgeMessage: Mark message as successfully processed
//     OR let lease expire → message returns to queue for retry
//  5. After max_attempts exhausted → message moves to DLQ
//
// gRPC vs REST:
// - gRPC: Preferred for high-throughput, low-latency scenarios
// - REST: Convenient for browser/curl access, debugging, simple integrations
//
// Error handling:
// - Use gRPC status codes (InvalidArgument, NotFound, AlreadyExists, etc.)
// - Error details in status.Details() for validation errors
type QueueServiceServer interface {
	// CreateQueue creates a new queue with specified configuration.
	//
	// Use to:
	// - Define retry behavior (max_attempts, lease_duration)
	// - Set up dead letter queue for failed messages
	// - Configure priority handling
	// - Enforce message schemas
	//
	// Example:
	//
	//	POST /v1/queues
	//	{
	//	  "name": "order-processing",
	//	  "metadata": {
	//	    "default_max_attempts": 3,
	//	    "lease_duration": "300s",
	//	    "auto_create_dlq": true
	//	  }
	//	}
	//
	// Returns: success status
	// Errors:
	//   - AlreadyExists: Queue with this name exists
	//   - InvalidArgument: Invalid configuration (negative lease_duration, etc.)
	CreateQueue(context.Context, *CreateQueueRequest) (*CreateQueueResponse, error)
	// DeleteQueue permanently deletes a queue and all its messages.
	//
	// WARNING: This operation is irreversible. All pending and running messages are lost.
	//
	// Use when:
	// - Decommissioning a feature
	// - Cleaning up test queues
	// - Removing unused queues
	//
	// Best practice: Drain queue first (stop posting, wait for workers to finish).
	//
	// Example:
	//
	//	DELETE /v1/queues/order-processing
	//
	// Returns: success status
	// Errors:
	//   - NotFound: Queue doesn't exist
	DeleteQueue(context.Context, *DeleteQueueRequest) (*DeleteQueueResponse, error)
	// ListQueues returns all queues in your ChronoQueue instance.
	//
	// Use for:
	// - Monitoring dashboards
	// - Queue discovery
	// - Debugging
	//
	// Example:
	//
	//	GET /v1/queues
	//
	// Returns: List of Queue objects with metadata
	ListQueues(context.Context, *ListQueuesRequest) (*ListQueuesResponse, error)
	// GetQueueState returns current queue statistics and health.
	//
	// Provides:
	// - Message counts by state (INVISIBLE, PENDING, RUNNING, COMPLETED, CANCELED, ERRORED)
	// - Earliest active lease or heartbeat deadline
	//
	// Use for:
	// - Health checks
	// - Autoscaling decisions (scale workers based on PENDING count)
	// - Alerting (high ERRORED count, DLQ growth)
	//
	// Example:
	//
	//	GET /v1/queues/order-processing/state
	//	Response:
	//	{
	//	  "stateCounts": {"INVISIBLE": "0", "PENDING": "150", "RUNNING": "10", "COMPLETED": "5420", "CANCELED": "0", "ERRORED": "3"}
	//	}
	//
	// Returns: state counts and the earliest active deadline
	GetQueueState(context.Context, *GetQueueStateRequest) (*GetQueueStateResponse, error)
	// PostMessage adds a new message to a queue.
	//
	// Use for:
	// - Asynchronous task execution
	// - Event-driven workflows
	// - Job scheduling
	// - Load leveling
	//
	// Features:
	// - Delayed execution (scheduled_time)
	// - Priority ordering
	// - Schema validation
	// - Deduplication by message_id within the queue
	// - Exclusive processing (exclusivity_key)
	//
	// Example - immediate execution:
	//
	//	POST /v1/queues/order-processing/messages
	//	{
	//	  "message": {
	//	    "messageId": "order-123",
	//	    "metadata": {
	//	      "payload": {"data": "..."},
	//	      "priority": 4
	//	    }
	//	  }
	//	}
	//
	// Example - delayed execution (send email in 1 hour):
	//
	//	{
	//	  "message": {
	//	    "messageId": "email-123",
	//	    "metadata": {
	//	      "payload": {"data": "..."},
	//	      "scheduledTime": "2024-12-01T15:00:00Z"
	//	    }
	//	  }
	//	}
	//
	// The caller must provide messageId. Returns success status.
	// Errors:
	//   - NotFound: Queue doesn't exist
	//   - InvalidArgument: Schema validation failed, invalid scheduled_time
	//   - AlreadyExists: Duplicate message_id in the queue
	PostMessage(context.Context, *PostMessageRequest) (*PostMessageResponse, error)
	// PostMessagesBulk posts multiple messages to a queue in a single operation.
	//
	// Supports two transaction modes:
	//   - ALL_OR_NOTHING: All messages succeed or all fail (atomic)
	//   - BEST_EFFORT: Independent processing, partial success allowed
	//
	// Limits:
	//   - Max 1000 messages per request
	//   - Max 1MB total payload size
	//
	// Errors:
	//   - NotFound: Queue doesn't exist
	//   - InvalidArgument: Too many messages, payload too large, invalid mode
	//   - FailedPrecondition: One or more messages failed in ALL_OR_NOTHING mode (entire batch rejected)
	//
	// Individual message errors are returned in the response with per-message error codes.
	PostMessagesBulk(context.Context, *PostMessagesBulkRequest) (*PostMessagesBulkResponse, error)
	// GetNextMessage retrieves the next available message for processing.
	//
	// This is the primary worker API. Call in a loop to continuously process messages.
	//
	// Behavior:
	// - Returns highest priority PENDING message
	// - Message moves to RUNNING state
	// - Lease timer starts (worker has lease_duration to process)
	// - If lease expires without ACK → message returns to PENDING for retry
	//
	// Concurrency:
	//   - Multiple workers can call simultaneously
	//   - Each worker gets a different message (no duplicates)
	//   - EXCLUSIVE queues require their configured exclusivity_key and allow one
	//     RUNNING message until it is acknowledged, failed, or reclaimed
	//
	// Example worker loop:
	//
	//	for {
	//	    resp := client.GetNextMessage(ctx, &GetNextMessageRequest{
	//	        QueueName: "order-processing",
	//	        LeaseDuration: durationpb.New(5 * time.Minute),
	//	    })
	//	    if resp.Message == nil {
	//	        time.Sleep(1 * time.Second)  // No messages available
	//	        continue
	//	    }
	//
	//	    err := processMessage(resp.Message)
	//	    if err != nil {
	//	        // Let lease expire → automatic retry
	//	        continue
	//	    }
	//
	//	    client.AcknowledgeMessage(ctx, &AcknowledgeMessageRequest{
	//	        QueueName: "order-processing",
	//	        MessageId: resp.Message.MessageId,
	//	    })
	//	}
	//
	// Returns: Message (or empty if no messages available)
	// Errors:
	//   - NotFound: Queue doesn't exist
	GetNextMessage(context.Context, *GetNextMessageRequest) (*GetNextMessageResponse, error)
	// AcknowledgeMessage marks a message as successfully processed.
	//
	// Call this after successfully processing a message retrieved by GetNextMessage.
	//
	// Effects:
	// - Message moves to COMPLETED state
	// - Message retained or removed according to the queue retention policy
	// - Queue stats updated
	//
	// Important: attempt_id and worker_id from GetNextMessage are required and
	// must identify the active, unexpired lease.
	//
	// Example:
	//
	//	POST /v1/queues/order-processing/messages/msg-123:acknowledge
	//
	// Returns: success status
	// Errors:
	//   - NotFound: Message doesn't exist or already acknowledged
	//   - DeadlineExceeded: Lease already expired
	AcknowledgeMessage(context.Context, *AcknowledgeMessageRequest) (*AcknowledgeMessageResponse, error)
	// CancelMessage cancels a pending message before it has been processed.
	//
	// Use when:
	// - Business logic invalidates the need for a message (order cancelled, user unsubscribed)
	// - Scheduled messages no longer needed (event rescheduled, task no longer relevant)
	// - Cleanup operations (purge old scheduled notifications)
	//
	// Producer-side operation: Only messages in INVISIBLE or PENDING state can be cancelled.
	// Messages already being processed (RUNNING) cannot be cancelled - use application-level
	// cancellation logic instead.
	//
	// Effects:
	// - Message moves to CANCELED state
	// - Message removed from processing queue
	// - Message retained based on retention policy (soft delete)
	// - Queue stats updated
	//
	// Example - cancel scheduled reminder:
	//
	//	POST /v1/queues/notifications/messages/reminder-456:cancel
	//
	// Example - cancel all pending messages for a user:
	//
	//	foreach messageId in userMessages:
	//	    CancelMessage(queueName, messageId)
	//
	// Returns: success status
	// Errors:
	//   - NotFound: Message doesn't exist
	//   - FailedPrecondition: Message is RUNNING, COMPLETED, ERRORED, or already CANCELED
	CancelMessage(context.Context, *CancelMessageRequest) (*CancelMessageResponse, error)
	// RenewMessageLease extends the processing time for a message.
	//
	// Use when:
	// - Processing takes longer than expected
	// - Long-running batch operations
	// - External API calls with unpredictable latency
	//
	// Call periodically during processing to prevent lease expiration.
	// attempt_id and worker_id from GetNextMessage are required and must identify
	// the active, unexpired lease.
	// An omitted lease_duration uses the queue/message extend_step. Renewal fails
	// without consuming a renewal when no positive extension remains.
	//
	// Example pattern (heartbeat-style lease renewal):
	//
	//	msg := getNextMessage()
	//	done := make(chan bool)
	//
	//	go func() {
	//	    ticker := time.NewTicker(leaseDuration / 2)
	//	    defer ticker.Stop()
	//	    for {
	//	        select {
	//	        case <-ticker.C:
	//	            renewMessageLease(msg.MessageId)
	//	        case <-done:
	//	            return
	//	        }
	//	    }
	//	}()
	//
	//	processMessage(msg)
	//	close(done)
	//	acknowledgeMessage(msg.MessageId)
	//
	// Returns: remaining lease time and current state
	// Errors:
	//   - NotFound: Message doesn't exist or already completed
	//   - FailedPrecondition: Message not in RUNNING state
	RenewMessageLease(context.Context, *RenewMessageLeaseRequest) (*RenewMessageLeaseResponse, error)
	// PeekQueueMessages views messages without leasing them.
	//
	// Use for:
	// - Debugging (inspect message payloads)
	// - Monitoring (see what's pending)
	// - Admin dashboards
	//
	// Does NOT:
	// - Change message state
	// - Create leases
	// - Affect message ordering
	//
	// Example:
	//
	//	GET /v1/queues/order-processing/messages:peek?page_size=10
	//
	// Returns: One deterministically ordered page of pending messages.
	PeekQueueMessages(context.Context, *PeekQueueMessagesRequest) (*PeekQueueMessagesResponse, error)
	// SendMessageHeartBeat indicates a worker is still processing a message.
	//
	// Alternative to RenewMessageLease that records worker liveness and extends
	// the lease to the configured heartbeat timeout.
	// attempt_id and worker_id from GetNextMessage are required and must identify
	// the active, unexpired lease.
	//
	// Example:
	//
	//	POST /v1/queues/order-processing/messages:heartbeat
	//	{
	//	  "messageId": "msg-123",
	//	  "attemptId": "attempt-123",
	//	  "workerId": "worker-1"
	//	}
	//
	// Returns: remaining lease time and current state
	SendMessageHeartBeat(context.Context, *SendMessageHeartBeatRequest) (*SendMessageHeartBeatResponse, error)
	// CreateSchedule creates a recurring message posting schedule.
	//
	// Use for:
	// - Cron-style job scheduling (daily reports, hourly cleanup)
	// - Business calendar scheduling (first business day of month)
	// - Recurring notifications (reminders, alerts)
	// - Periodic batch processing
	//
	// Supports:
	// - Simple cron expressions: "0 9 * * 1-5" (weekdays at 9 AM)
	// - Complex calendar rules: "last Friday of each quarter"
	// - Timezone-aware scheduling
	// - Holiday handling
	//
	// Example - daily report at 8 AM EST:
	//
	//	POST /v1/schedules
	//	{
	//	  "schedule": {
	//	    "schedule_id": "daily-sales-report",
	//	    "metadata": {
	//	      "cron_schedule": "0 8 * * *",
	//	      "timezone": "America/New_York",
	//	      "queue_name": "reports",
	//	      "payload": {...}
	//	    }
	//	  }
	//	}
	//
	// Returns: success status
	// Errors:
	//   - AlreadyExists: schedule_id already in use
	//   - InvalidArgument: Invalid cron expression or calendar rule
	CreateSchedule(context.Context, *CreateScheduleRequest) (*CreateScheduleResponse, error)
	// DeleteSchedule permanently removes a schedule.
	//
	// Effects:
	// - Schedule stops creating new messages
	// - Existing messages already posted remain in queue
	// - Schedule history is preserved
	//
	// Example:
	//
	//	DELETE /v1/schedules/daily-sales-report
	//
	// Returns: success status
	// Errors:
	//   - NotFound: Schedule doesn't exist
	DeleteSchedule(context.Context, *DeleteScheduleRequest) (*DeleteScheduleResponse, error)
	// GetSchedule retrieves schedule details and current state.
	//
	// Returns:
	// - Schedule configuration
	// - Current state (SCHEDULED, PAUSED, CANCELED, ERRORED)
	// - Next execution time
	// - Last execution time
	// - Execution count
	//
	// Example:
	//
	//	GET /v1/schedules/daily-sales-report
	//
	// Returns: Schedule object
	// Errors:
	//   - NotFound: Schedule doesn't exist
	GetSchedule(context.Context, *GetScheduleRequest) (*GetScheduleResponse, error)
	// ListSchedules returns all schedules.
	//
	// Use for:
	// - Admin dashboards
	// - Monitoring active schedules
	// - Discovering schedules
	//
	// Example:
	//
	//	GET /v1/schedules
	//
	// Returns: List of Schedule objects
	ListSchedules(context.Context, *ListSchedulesRequest) (*ListSchedulesResponse, error)
	// GetScheduleHistory returns execution history for a schedule.
	//
	// Shows:
	// - Past executions with timestamps
	// - Messages created by each execution
	// - Success/failure status
	//
	// Use for:
	// - Debugging missed executions
	// - Auditing schedule activity
	// - Verifying schedule correctness
	//
	// Example:
	//
	//	GET /v1/schedules/daily-sales-report/history
	//
	// Returns: ScheduleHistory with execution records
	GetScheduleHistory(context.Context, *GetScheduleHistoryRequest) (*GetScheduleHistoryResponse, error)
	// PauseSchedule temporarily stops a schedule from creating messages.
	//
	// Use when:
	// - Temporarily disabling a feature
	// - During maintenance windows
	// - Debugging issues
	//
	// Effects:
	// - Schedule state → PAUSED
	// - No new messages created
	// - Can be resumed later with ResumeSchedule
	//
	// Example:
	//
	//	POST /v1/schedules/daily-sales-report:pause
	//
	// Returns: success status
	// Errors:
	//   - NotFound: Schedule doesn't exist
	//   - FailedPrecondition: Schedule not in SCHEDULED state
	PauseSchedule(context.Context, *PauseScheduleRequest) (*PauseScheduleResponse, error)
	// ResumeSchedule reactivates a paused schedule.
	//
	// Effects:
	// - Schedule state → SCHEDULED
	// - Resets the max_messages execution counter
	// - Retains next_run; an overdue run is eligible immediately after resume
	// - Does NOT backfill missed executions during pause
	//
	// Example:
	//
	//	POST /v1/schedules/daily-sales-report:resume
	//
	// Returns: success status
	// Errors:
	//   - NotFound: Schedule doesn't exist
	//   - FailedPrecondition: Schedule not in PAUSED state
	ResumeSchedule(context.Context, *ResumeScheduleRequest) (*ResumeScheduleResponse, error)
	// GetDLQMessages retrieves messages from a dead letter queue.
	//
	// Dead letter queues contain:
	// - Messages that exhausted retry attempts
	// - Messages that caused persistent errors
	// - Messages rejected by workers
	//
	// Use for:
	// - Investigating failures
	// - Manual reprocessing after fixing bugs
	// - Identifying systematic issues
	//
	// Example:
	//
	//	GET /v1/dlq/order-dlq/messages?page_size=50
	//
	// Returns: List of failed messages with error details
	GetDLQMessages(context.Context, *GetDLQMessagesRequest) (*GetDLQMessagesResponse, error)
	// RequeueFromDLQ moves a message from DLQ to the required target queue.
	//
	// Use after:
	// - Fixing bugs that caused failures
	// - Resolving external service outages
	// - Correcting data issues
	//
	// Effects:
	// - Message removed from DLQ
	// - Message added to targetQueue as PENDING
	// - attempts_left always reset
	//
	// Example:
	//
	//	POST /v1/dlq/order-dlq/messages/msg-123:requeue
	//	{
	//	  "targetQueue": "orders"
	//	}
	//
	// Returns: success status
	// Errors:
	//   - NotFound: Message not in DLQ
	//   - NotFound: Target queue does not exist
	//   - InvalidArgument: targetQueue is empty
	RequeueFromDLQ(context.Context, *RequeueFromDLQRequest) (*RequeueFromDLQResponse, error)
	// DeleteFromDLQ permanently removes a message from the DLQ.
	//
	// Use when:
	// - Message is not recoverable
	// - Data is no longer relevant
	// - Cleaning up test data
	//
	// WARNING: This is permanent. Message cannot be recovered.
	//
	// Example:
	//
	//	DELETE /v1/dlq/order-dlq/messages/msg-123
	//
	// Returns: success status
	// Errors:
	//   - NotFound: Message not in DLQ
	DeleteFromDLQ(context.Context, *DeleteFromDLQRequest) (*DeleteFromDLQResponse, error)
	// PurgeDLQ removes all messages from a dead letter queue.
	//
	// Use when:
	// - Cleaning up after incident
	// - Clearing test data
	// - DLQ too large to manage individually
	//
	// WARNING: This is irreversible. All DLQ messages are permanently deleted.
	//
	// Example:
	//
	//	POST /v1/dlq/order-dlq:purge
	//
	// Returns: Whether the purge succeeded
	PurgeDLQ(context.Context, *PurgeDLQRequest) (*PurgeDLQResponse, error)
	// GetDLQStats returns statistics about a dead letter queue.
	//
	// Provides:
	// - Message count
	// - Queue creation and update timestamps
	//
	// Use for:
	// - Monitoring DLQ health
	// - Alerting on DLQ growth
	// - Identifying systemic issues
	//
	// Example:
	//
	//	GET /v1/dlq/order-dlq/stats
	//
	// Returns: DLQ statistics
	GetDLQStats(context.Context, *GetDLQStatsRequest) (*GetDLQStatsResponse, error)
	// ValidateCalendarSchedule checks if a calendar schedule is valid.
	//
	// Validates:
	// - Calendar rule correctness
	// - Timezone validity
	// - Holiday rule logic
	//
	// Use before CreateSchedule to catch configuration errors.
	//
	// Example:
	//
	//	POST /v1/calendar-schedules:validate
	//	{
	//	  "calendar_schedule": {...}
	//	}
	//
	// Returns: Validation result with errors if invalid
	ValidateCalendarSchedule(context.Context, *ValidateCalendarScheduleRequest) (*ValidateCalendarScheduleResponse, error)
	// PreviewCalendarSchedule shows next N execution times for a schedule.
	//
	// Use to:
	// - Verify schedule behaves as expected
	// - Test complex calendar rules
	// - Confirm timezone handling
	// - Preview holiday exceptions
	//
	// Example:
	//
	//	POST /v1/calendar-schedules:preview
	//	{
	//	  "calendar_schedule": {...},
	//	  "count": 10  // Next 10 executions
	//	}
	//
	//	Response:
	//	{
	//	  "next_runs": [
	//	    "2024-01-02T09:00:00Z",
	//	    "2024-01-03T09:00:00Z",
	//	    "2024-01-04T09:00:00Z",
	//	    ...
	//	  ]
	//	}
	//
	// Returns: List of upcoming execution timestamps
	PreviewCalendarSchedule(context.Context, *PreviewCalendarScheduleRequest) (*PreviewCalendarScheduleResponse, error)
	// RegisterSchema creates the next version of a message validation schema.
	//
	// Use for:
	// - Enforcing message structure
	// - API contract validation
	// - Data quality checks
	// - Type safety
	//
	// Schema versioning:
	// - Each schema has a schema_id and a server-assigned version number
	// - Multiple versions can coexist
	// - Queues reference schema_id (use highest active version)
	//
	// Example:
	//
	//	POST /v1/schemas
	//	{
	//	  "schema_id": "order-schema",
	//	  "name": "Order schema",
	//	  "content": "{...JSON Schema...}",
	//	  "content_type": "json-schema"
	//	}
	//
	// Returns: Registered schema
	// Errors:
	//   - InvalidArgument: Invalid schema syntax
	RegisterSchema(context.Context, *RegisterSchemaRequest) (*RegisterSchemaResponse, error)
	// GetSchema retrieves a specific schema version.
	//
	// Example:
	//
	//	GET /v1/schemas/order-schema/versions/2
	//
	// Returns: Schema details
	// Errors:
	//   - NotFound: Schema not found
	GetSchema(context.Context, *GetSchemaRequest) (*GetSchemaResponse, error)
	// ListSchemas returns one summary for each registered schema family.
	//
	// Use for:
	// - Schema discovery
	// - Admin dashboards
	// - Schema management
	//
	// Example:
	//
	//	GET /v1/schemas
	//
	// Returns: Latest matching version and aggregate version metadata for each family
	ListSchemas(context.Context, *ListSchemasRequest) (*ListSchemasResponse, error)
	// DeleteSchema deactivates a schema version, or all versions when version is 0.
	//
	// Effects:
	// - Matching active schema versions are marked inactive
	// - Inactive versions remain addressable for validation history
	//
	// Example:
	//
	//	DELETE /v1/schemas/order-schema/versions/1
	//
	// Returns: Number of versions deactivated
	// Errors:
	//   - NotFound: Schema not found
	DeleteSchema(context.Context, *DeleteSchemaRequest) (*DeleteSchemaResponse, error)
	// ValidatePayload validates a payload against a schema without posting a message.
	//
	// Use for:
	// - Pre-flight validation
	// - Testing schema changes
	// - Client-side validation
	// - Development/debugging
	//
	// Example:
	//
	//	POST /v1/schemas/order-schema/versions/2:validate
	//	{
	//	  "payload": {
	//	    "data": "{\"orderId\": \"ORD-123\", ...}"
	//	  }
	//	}
	//
	// Returns: ValidationResult (valid=true or list of errors)
	ValidatePayload(context.Context, *ValidatePayloadRequest) (*ValidatePayloadResponse, error)
}

// UnimplementedQueueServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueueServiceServer struct{}

func (UnimplementedQueueServiceServer) CreateQueue(context.Context, *CreateQueueRequest) (*CreateQueueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateQueue not implemented")
}
func (UnimplementedQueueServiceServer) DeleteQueue(context.Context, *DeleteQueueRequest) (*DeleteQueueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteQueue not implemented")
}
func (UnimplementedQueueServiceServer) ListQueues(context.Context, *ListQueuesRequest) (*ListQueuesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListQueues not implemented")
}
func (UnimplementedQueueServiceServer) GetQueueState(context.Context, *GetQueueStateRequest) (*GetQueueStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQueueState not implemented")
}
func (UnimplementedQueueServiceServer) PostMessage(context.Context, *PostMessageRequest) (*PostMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostMessage not implemented")
}
func (UnimplementedQueueServiceServer) PostMessagesBulk(context.Context, *PostMessagesBulkRequest) (*PostMessagesBulkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostMessagesBulk not implemented")
}
func (UnimplementedQueueServiceServer) GetNextMessage(context.Context, *GetNextMessageRequest) (*GetNextMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNextMessage not implemented")
}
func (UnimplementedQueueServiceServer) AcknowledgeMessage(context.Context, *AcknowledgeMessageRequest) (*AcknowledgeMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcknowledgeMessage not implemented")
}
func (UnimplementedQueueServiceServer) CancelMessage(context.Context, *CancelMessageRequest) (*CancelMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelMessage not implemented")
}
func (UnimplementedQueueServiceServer) RenewMessageLease(context.Context, *RenewMessageLeaseRequest) (*RenewMessageLeaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenewMessageLease not implemented")
}
func (UnimplementedQueueServiceServer) PeekQueueMessages(context.Context, *PeekQueueMessagesRequest) (*PeekQueueMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PeekQueueMessages not implemented")
}
func (UnimplementedQueueServiceServer) SendMessageHeartBeat(context.Context, *SendMessageHeartBeatRequest) (*SendMessageHeartBeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessageHeartBeat not implemented")
}
func (UnimplementedQueueServiceServer) CreateSchedule(context.Context, *CreateScheduleRequest) (*CreateScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSchedule not implemented")
}
func (UnimplementedQueueServiceServer) DeleteSchedule(context.Context, *DeleteScheduleRequest) (*DeleteScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSchedule not implemented")
}
func (UnimplementedQueueServiceServer) GetSchedule(context.Context, *GetScheduleRequest) (*GetScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSchedule not implemented")
}
func (UnimplementedQueueServiceServer) ListSchedules(context.Context, *ListSchedulesRequest) (*ListSchedulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSchedules not implemented")
}
func (UnimplementedQueueServiceServer) GetScheduleHistory(context.Context, *GetScheduleHistoryRequest) (*GetScheduleHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScheduleHistory not implemented")
}
func (UnimplementedQueueServiceServer) PauseSchedule(context.Context, *PauseScheduleRequest) (*PauseScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PauseSchedule not implemented")
}
func (UnimplementedQueueServiceServer) ResumeSchedule(context.Context, *ResumeScheduleRequest) (*ResumeScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumeSchedule not implemented")
}
func (UnimplementedQueueServiceServer) GetDLQMessages(context.Context, *GetDLQMessagesRequest) (*GetDLQMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDLQMessages not implemented")
}
func (UnimplementedQueueServiceServer) RequeueFromDLQ(context.Context, *RequeueFromDLQRequest) (*RequeueFromDLQResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequeueFromDLQ not implemented")
}
func (UnimplementedQueueServiceServer) DeleteFromDLQ(context.Context, *DeleteFromDLQRequest) (*DeleteFromDLQResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFromDLQ not implemented")
}
func (UnimplementedQueueServiceServer) PurgeDLQ(context.Context, *PurgeDLQRequest) (*PurgeDLQResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PurgeDLQ not implemented")
}
func (UnimplementedQueueServiceServer) GetDLQStats(context.Context, *GetDLQStatsRequest) (*GetDLQStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDLQStats not implemented")
}
func (UnimplementedQueueServiceServer) ValidateCalendarSchedule(context.Context, *ValidateCalendarScheduleRequest) (*ValidateCalendarScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateCalendarSchedule not implemented")
}
func (UnimplementedQueueServiceServer) PreviewCalendarSchedule(context.Context, *PreviewCalendarScheduleRequest) (*PreviewCalendarScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PreviewCalendarSchedule not implemented")
}
func (UnimplementedQueueServiceServer) RegisterSchema(context.Context, *RegisterSchemaRequest) (*RegisterSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterSchema not implemented")
}
func (UnimplementedQueueServiceServer) GetSchema(context.Context, *GetSchemaRequest) (*GetSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSchema not implemented")
}
func (UnimplementedQueueServiceServer) ListSchemas(context.Context, *ListSchemasRequest) (*ListSchemasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSchemas not implemented")
}
func (UnimplementedQueueServiceServer) DeleteSchema(context.Context, *DeleteSchemaRequest) (*DeleteSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSchema not implemented")
}
func (UnimplementedQueueServiceServer) ValidatePayload(context.Context, *ValidatePayloadRequest) (*ValidatePayloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidatePayload not implemented")
}
func (UnimplementedQueueServiceServer) testEmbeddedByValue() {}

// UnsafeQueueServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueueServiceServer will
// result in compilation errors.
type UnsafeQueueServiceServer interface {
	mustEmbedUnimplementedQueueServiceServer()
}

func RegisterQueueServiceServer(s grpc.ServiceRegistrar, srv QueueServiceServer) {
	// If the following call pancis, it indicates UnimplementedQueueServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QueueService_ServiceDesc, srv)
}

func _QueueService_CreateQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).CreateQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_CreateQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).CreateQueue(ctx, req.(*CreateQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_DeleteQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).DeleteQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_DeleteQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).DeleteQueue(ctx, req.(*DeleteQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_ListQueues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListQueuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).ListQueues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_ListQueues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).ListQueues(ctx, req.(*ListQueuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_GetQueueState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQueueStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).GetQueueState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_GetQueueState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).GetQueueState(ctx, req.(*GetQueueStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_PostMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).PostMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_PostMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).PostMessage(ctx, req.(*PostMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_PostMessagesBulk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostMessagesBulkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).PostMessagesBulk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_PostMessagesBulk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).PostMessagesBulk(ctx, req.(*PostMessagesBulkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_GetNextMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNextMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).GetNextMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_GetNextMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).GetNextMessage(ctx, req.(*GetNextMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_AcknowledgeMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcknowledgeMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).AcknowledgeMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_AcknowledgeMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).AcknowledgeMessage(ctx, req.(*AcknowledgeMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_CancelMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).CancelMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_CancelMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).CancelMessage(ctx, req.(*CancelMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_RenewMessageLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewMessageLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).RenewMessageLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_RenewMessageLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).RenewMessageLease(ctx, req.(*RenewMessageLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_PeekQueueMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeekQueueMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).PeekQueueMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_PeekQueueMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).PeekQueueMessages(ctx, req.(*PeekQueueMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_SendMessageHeartBeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageHeartBeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).SendMessageHeartBeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_SendMessageHeartBeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).SendMessageHeartBeat(ctx, req.(*SendMessageHeartBeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_CreateSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).CreateSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_CreateSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).CreateSchedule(ctx, req.(*CreateScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_DeleteSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).DeleteSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_DeleteSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).DeleteSchedule(ctx, req.(*DeleteScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_GetSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).GetSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_GetSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).GetSchedule(ctx, req.(*GetScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_ListSchedules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSchedulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).ListSchedules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_ListSchedules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).ListSchedules(ctx, req.(*ListSchedulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_GetScheduleHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScheduleHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).GetScheduleHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_GetScheduleHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).GetScheduleHistory(ctx, req.(*GetScheduleHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_PauseSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).PauseSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_PauseSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).PauseSchedule(ctx, req.(*PauseScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_ResumeSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).ResumeSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_ResumeSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).ResumeSchedule(ctx, req.(*ResumeScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_GetDLQMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDLQMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).GetDLQMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_GetDLQMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).GetDLQMessages(ctx, req.(*GetDLQMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_RequeueFromDLQ_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequeueFromDLQRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).RequeueFromDLQ(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_RequeueFromDLQ_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).RequeueFromDLQ(ctx, req.(*RequeueFromDLQRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_DeleteFromDLQ_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFromDLQRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).DeleteFromDLQ(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_DeleteFromDLQ_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).DeleteFromDLQ(ctx, req.(*DeleteFromDLQRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_PurgeDLQ_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurgeDLQRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).PurgeDLQ(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_PurgeDLQ_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).PurgeDLQ(ctx, req.(*PurgeDLQRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_GetDLQStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDLQStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).GetDLQStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_GetDLQStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).GetDLQStats(ctx, req.(*GetDLQStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_ValidateCalendarSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateCalendarScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).ValidateCalendarSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_ValidateCalendarSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).ValidateCalendarSchedule(ctx, req.(*ValidateCalendarScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_PreviewCalendarSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreviewCalendarScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).PreviewCalendarSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_PreviewCalendarSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).PreviewCalendarSchedule(ctx, req.(*PreviewCalendarScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_RegisterSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).RegisterSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_RegisterSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).RegisterSchema(ctx, req.(*RegisterSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_GetSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).GetSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_GetSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).GetSchema(ctx, req.(*GetSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_ListSchemas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSchemasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).ListSchemas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_ListSchemas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).ListSchemas(ctx, req.(*ListSchemasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_DeleteSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).DeleteSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_DeleteSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).DeleteSchema(ctx, req.(*DeleteSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_ValidatePayload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidatePayloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).ValidatePayload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_ValidatePayload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).ValidatePayload(ctx, req.(*ValidatePayloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QueueService_ServiceDesc is the grpc.ServiceDesc for QueueService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QueueService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nzovu.api.queueservice.v1.QueueService",
	HandlerType: (*QueueServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateQueue",
			Handler:    _QueueService_CreateQueue_Handler,
		},
		{
			MethodName: "DeleteQueue",
			Handler:    _QueueService_DeleteQueue_Handler,
		},
		{
			MethodName: "ListQueues",
			Handler:    _QueueService_ListQueues_Handler,
		},
		{
			MethodName: "GetQueueState",
			Handler:    _QueueService_GetQueueState_Handler,
		},
		{
			MethodName: "PostMessage",
			Handler:    _QueueService_PostMessage_Handler,
		},
		{
			MethodName: "PostMessagesBulk",
			Handler:    _QueueService_PostMessagesBulk_Handler,
		},
		{
			MethodName: "GetNextMessage",
			Handler:    _QueueService_GetNextMessage_Handler,
		},
		{
			MethodName: "AcknowledgeMessage",
			Handler:    _QueueService_AcknowledgeMessage_Handler,
		},
		{
			MethodName: "CancelMessage",
			Handler:    _QueueService_CancelMessage_Handler,
		},
		{
			MethodName: "RenewMessageLease",
			Handler:    _QueueService_RenewMessageLease_Handler,
		},
		{
			MethodName: "PeekQueueMessages",
			Handler:    _QueueService_PeekQueueMessages_Handler,
		},
		{
			MethodName: "SendMessageHeartBeat",
			Handler:    _QueueService_SendMessageHeartBeat_Handler,
		},
		{
			MethodName: "CreateSchedule",
			Handler:    _QueueService_CreateSchedule_Handler,
		},
		{
			MethodName: "DeleteSchedule",
			Handler:    _QueueService_DeleteSchedule_Handler,
		},
		{
			MethodName: "GetSchedule",
			Handler:    _QueueService_GetSchedule_Handler,
		},
		{
			MethodName: "ListSchedules",
			Handler:    _QueueService_ListSchedules_Handler,
		},
		{
			MethodName: "GetScheduleHistory",
			Handler:    _QueueService_GetScheduleHistory_Handler,
		},
		{
			MethodName: "PauseSchedule",
			Handler:    _QueueService_PauseSchedule_Handler,
		},
		{
			MethodName: "ResumeSchedule",
			Handler:    _QueueService_ResumeSchedule_Handler,
		},
		{
			MethodName: "GetDLQMessages",
			Handler:    _QueueService_GetDLQMessages_Handler,
		},
		{
			MethodName: "RequeueFromDLQ",
			Handler:    _QueueService_RequeueFromDLQ_Handler,
		},
		{
			MethodName: "DeleteFromDLQ",
			Handler:    _QueueService_DeleteFromDLQ_Handler,
		},
		{
			MethodName: "PurgeDLQ",
			Handler:    _QueueService_PurgeDLQ_Handler,
		},
		{
			MethodName: "GetDLQStats",
			Handler:    _QueueService_GetDLQStats_Handler,
		},
		{
			MethodName: "ValidateCalendarSchedule",
			Handler:    _QueueService_ValidateCalendarSchedule_Handler,
		},
		{
			MethodName: "PreviewCalendarSchedule",
			Handler:    _QueueService_PreviewCalendarSchedule_Handler,
		},
		{
			MethodName: "RegisterSchema",
			Handler:    _QueueService_RegisterSchema_Handler,
		},
		{
			MethodName: "GetSchema",
			Handler:    _QueueService_GetSchema_Handler,
		},
		{
			MethodName: "ListSchemas",
			Handler:    _QueueService_ListSchemas_Handler,
		},
		{
			MethodName: "DeleteSchema",
			Handler:    _QueueService_DeleteSchema_Handler,
		},
		{
			MethodName: "ValidatePayload",
			Handler:    _QueueService_ValidatePayload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/queueservice/v1/service.proto",
}
