// Nzovu Schema API v1
//
// This file defines structures for message payload validation.
// Schemas ensure message payloads conform to expected structure before processing.
//
// Benefits:
// - Catch malformed messages early (before workers process them)
// - Enforce data contracts between producers and consumers
// - Support schema evolution with versioning
// - Enable type-safe deserialization in strongly-typed languages
//
// Common use cases:
// - API request/response validation
// - Event schema enforcement in event-driven architectures
// - Data quality checks for analytics pipelines
// - Integration contract testing

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: proto/schema/v1/schema.proto

package schema

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorCode enum for standardized validation error classification.
//
// Use these codes to:
// - Handle specific error types programmatically
// - Display user-friendly error messages
// - Track validation failure metrics by category
//
// Mapping to JSON Schema validation errors:
//
//	REQUIRED_FIELD_MISSING = "required" keyword
//	INVALID_TYPE = "type" keyword
//	PATTERN_MISMATCH = "pattern" keyword
//	VALUE_OUT_OF_RANGE = "minimum", "maximum", "exclusiveMinimum", "exclusiveMaximum"
//	ARRAY_LENGTH_INVALID = "minItems", "maxItems"
//	ENUM_VALUE_INVALID = "enum" keyword
type ErrorCode int32

const (
	// UNKNOWN_ERROR: Unclassified validation error.
	// Check message field for details.
	ErrorCode_UNKNOWN_ERROR ErrorCode = 0
	// REQUIRED_FIELD_MISSING: A required field is absent.
	// Corresponds to JSON Schema "required" keyword.
	ErrorCode_REQUIRED_FIELD_MISSING ErrorCode = 1
	// INVALID_TYPE: Field has wrong type.
	// Example: Expected integer, got string.
	// Corresponds to JSON Schema "type" keyword.
	ErrorCode_INVALID_TYPE ErrorCode = 2
	// INVALID_FORMAT: Field value doesn't match expected format.
	// Example: Invalid email, UUID, date-time, URI.
	// Corresponds to JSON Schema "format" keyword.
	ErrorCode_INVALID_FORMAT ErrorCode = 3
	// PATTERN_MISMATCH: String doesn't match regex pattern.
	// Example: Phone number doesn't match "^\d{3}-\d{3}-\d{4}$".
	// Corresponds to JSON Schema "pattern" keyword.
	ErrorCode_PATTERN_MISMATCH ErrorCode = 4
	// VALUE_OUT_OF_RANGE: Numeric value outside allowed range.
	// Example: Age is -5 (minimum is 0).
	// Corresponds to JSON Schema "minimum", "maximum", etc.
	ErrorCode_VALUE_OUT_OF_RANGE ErrorCode = 5
	// ARRAY_LENGTH_INVALID: Array has wrong number of elements.
	// Example: Order must have 1-10 items, got 0.
	// Corresponds to JSON Schema "minItems", "maxItems".
	ErrorCode_ARRAY_LENGTH_INVALID ErrorCode = 6
	// OBJECT_PROPERTIES_INVALID: Object has wrong properties.
	// Example: Missing required nested field.
	// Corresponds to JSON Schema object validation.
	ErrorCode_OBJECT_PROPERTIES_INVALID ErrorCode = 7
	// ADDITIONAL_PROPERTIES_NOT_ALLOWED: Object has unexpected fields.
	// Occurs when schema sets "additionalProperties": false.
	ErrorCode_ADDITIONAL_PROPERTIES_NOT_ALLOWED ErrorCode = 8
	// ENUM_VALUE_INVALID: Value not in allowed enum set.
	// Example: status must be "pending" or "completed", got "unknown".
	// Corresponds to JSON Schema "enum" keyword.
	ErrorCode_ENUM_VALUE_INVALID ErrorCode = 9
	// SCHEMA_NOT_FOUND: Referenced schema doesn't exist.
	// Occurs when queue references non-existent schema_id.
	ErrorCode_SCHEMA_NOT_FOUND ErrorCode = 10
	// CONTENT_TYPE_INVALID: Payload content_type incompatible with schema.
	// Example: Schema expects JSON, payload is "application/protobuf".
	ErrorCode_CONTENT_TYPE_INVALID ErrorCode = 11
	// PAYLOAD_SIZE_EXCEEDED: Payload exceeds size limit.
	// Nzovu has a default 1MB payload limit.
	ErrorCode_PAYLOAD_SIZE_EXCEEDED ErrorCode = 12
	// SCHEMA_VALIDATION_FAILED: Schema content itself is invalid.
	// Occurs when registering schema with malformed content.
	ErrorCode_SCHEMA_VALIDATION_FAILED ErrorCode = 13
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:  "UNKNOWN_ERROR",
		1:  "REQUIRED_FIELD_MISSING",
		2:  "INVALID_TYPE",
		3:  "INVALID_FORMAT",
		4:  "PATTERN_MISMATCH",
		5:  "VALUE_OUT_OF_RANGE",
		6:  "ARRAY_LENGTH_INVALID",
		7:  "OBJECT_PROPERTIES_INVALID",
		8:  "ADDITIONAL_PROPERTIES_NOT_ALLOWED",
		9:  "ENUM_VALUE_INVALID",
		10: "SCHEMA_NOT_FOUND",
		11: "CONTENT_TYPE_INVALID",
		12: "PAYLOAD_SIZE_EXCEEDED",
		13: "SCHEMA_VALIDATION_FAILED",
	}
	ErrorCode_value = map[string]int32{
		"UNKNOWN_ERROR":                     0,
		"REQUIRED_FIELD_MISSING":            1,
		"INVALID_TYPE":                      2,
		"INVALID_FORMAT":                    3,
		"PATTERN_MISMATCH":                  4,
		"VALUE_OUT_OF_RANGE":                5,
		"ARRAY_LENGTH_INVALID":              6,
		"OBJECT_PROPERTIES_INVALID":         7,
		"ADDITIONAL_PROPERTIES_NOT_ALLOWED": 8,
		"ENUM_VALUE_INVALID":                9,
		"SCHEMA_NOT_FOUND":                  10,
		"CONTENT_TYPE_INVALID":              11,
		"PAYLOAD_SIZE_EXCEEDED":             12,
		"SCHEMA_VALIDATION_FAILED":          13,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_schema_v1_schema_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_proto_schema_v1_schema_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_schema_v1_schema_proto_rawDescGZIP(), []int{0}
}

// Schema defines a message validation schema.
//
// Nzovu validates message payloads against schemas before accepting them.
// This prevents invalid messages from entering your queues.
//
// Schema evolution:
// 1. Create v1: Initial schema
// 2. Create v2: Add optional fields (backward compatible)
// 3. Update producers to v2
// 4. Update consumers to v2
// 5. Deprecate v1 when all clients upgraded
//
// Example - Order schema:
//
//	schema := &schema.Schema{
//	    SchemaId: "order-schema",
//	    Version: 1,
//	    Name: "Order Validation Schema",
//	    Content: `{
//	        "type": "object",
//	        "required": ["orderId", "customerId", "items"],
//	        "properties": {
//	            "orderId": {"type": "string", "pattern": "^ORD-[0-9]+$"},
//	            "customerId": {"type": "string"},
//	            "items": {
//	                "type": "array",
//	                "minItems": 1,
//	                "items": {
//	                    "type": "object",
//	                    "required": ["productId", "quantity"],
//	                    "properties": {
//	                        "productId": {"type": "string"},
//	                        "quantity": {"type": "integer", "minimum": 1}
//	                    }
//	                }
//	            },
//	            "totalAmount": {"type": "number", "minimum": 0}
//	        }
//	    }`,
//	    ContentType: "json-schema",
//	    IsActive: true,
//	}
//
// Then reference in Queue:
//
//	queue := &queue.Queue{
//	    Name: "order-processing",
//	    Metadata: &queue.QueueMetadata{
//	        SchemaId: "order-schema",
//	        SchemaRequired: true,  // Reject invalid messages
//	    },
//	}
type Schema struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// schema_id: Unique identifier for this schema family.
	// All versions of the same schema share this ID.
	// Example: "order-schema", "user-event-schema"
	SchemaId string `protobuf:"bytes,1,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	// version: Schema version number (positive integer).
	// Increment when making changes to the schema.
	// Semantic versioning recommended:
	//
	//	v1 -> v2: backward compatible changes (add optional fields)
	//	v2 -> v3: breaking changes (remove/rename fields, change types)
	Version int32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	// name: Human-readable schema name.
	// Example: "Order Validation Schema v2", "User Registration Event"
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// description: Detailed description of what this schema validates.
	// Include changelog for new versions.
	// Example: "v2: Added optional 'discountCode' field. Removed deprecated 'legacyField'."
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// content: The actual validation schema.
	// JSON Schema Draft 7 document (https://json-schema.org/).
	// Size limit: 1MB
	Content string `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	// content_type: Schema format identifier.
	// Supported value: "json-schema" (default), using JSON Schema Draft 7.
	// Nzovu validates content syntax when registering schema.
	ContentType string `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// created_at: When this schema version was registered (Unix milliseconds).
	// Automatically set by Nzovu.
	CreatedAt int64 `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// updated_at: When this schema was last modified (Unix milliseconds).
	// Schemas are immutable after creation; updates create new versions.
	// This tracks metadata changes (name, description, is_active).
	UpdatedAt int64 `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// is_active: Whether this schema version can be used for validation.
	// Set to false to deprecate old versions.
	// Queues configured with this schema_id will use the highest active version.
	// Use case: Deactivate v1 after all clients migrate to v2.
	IsActive bool `protobuf:"varint,9,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	// metadata: Additional schema metadata.
	// Use for:
	//
	//	"owner": "team-checkout"
	//	"deprecation_date": "2025-01-01"
	//	"changelog_url": "https://..."
	//	"contact": "checkout-team@example.com"
	Metadata      map[string]string `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema) Reset() {
	*x = Schema{}
	mi := &file_proto_schema_v1_schema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema) ProtoMessage() {}

func (x *Schema) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schema_v1_schema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema.ProtoReflect.Descriptor instead.
func (*Schema) Descriptor() ([]byte, []int) {
	return file_proto_schema_v1_schema_proto_rawDescGZIP(), []int{0}
}

func (x *Schema) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *Schema) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Schema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Schema) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Schema) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Schema) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Schema) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Schema) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Schema) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Schema) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ValidationResult contains the outcome of payload validation.
//
// Returned by:
// - PostMessage API (if validation fails, message is rejected)
// - ValidatePayload API (dry-run validation before posting)
//
// Example - handling validation errors:
//
//	result, err := client.PostMessage(ctx, &queueservice.PostMessageRequest{...})
//	if err != nil {
//	    if status.Code(err) == codes.InvalidArgument {
//	        // Check err.Details() for ValidationResult
//	        for _, detail := range status.Convert(err).Details() {
//	            if vr, ok := detail.(*schema.ValidationResult); ok {
//	                for _, verr := range vr.Errors {
//	                    log.Printf("Field '%s' failed: %s", verr.Field, verr.Message)
//	                }
//	            }
//	        }
//	    }
//	}
type ValidationResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// valid: True if payload passed validation, false otherwise.
	Valid bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	// errors: List of validation errors (empty if valid = true).
	// Each error describes one validation rule violation.
	Errors []*ValidationError `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	// validated_at: When validation was performed (Unix milliseconds).
	ValidatedAt int64 `protobuf:"varint,3,opt,name=validated_at,json=validatedAt,proto3" json:"validated_at,omitempty"`
	// schema_id: Which schema was used for validation.
	SchemaId string `protobuf:"bytes,4,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	// schema_version: Which schema version was used.
	// Helps debug validation failures after schema upgrades.
	SchemaVersion int32 `protobuf:"varint,5,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationResult) Reset() {
	*x = ValidationResult{}
	mi := &file_proto_schema_v1_schema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationResult) ProtoMessage() {}

func (x *ValidationResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schema_v1_schema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationResult.ProtoReflect.Descriptor instead.
func (*ValidationResult) Descriptor() ([]byte, []int) {
	return file_proto_schema_v1_schema_proto_rawDescGZIP(), []int{1}
}

func (x *ValidationResult) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidationResult) GetErrors() []*ValidationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ValidationResult) GetValidatedAt() int64 {
	if x != nil {
		return x.ValidatedAt
	}
	return 0
}

func (x *ValidationResult) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *ValidationResult) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

// ValidationError provides detailed information about a validation failure.
//
// Each error describes:
// - Which field failed (field path)
// - Why it failed (error_code)
// - Human-readable explanation (message)
// - Additional context (details)
//
// Example errors:
//
//	Field "payload.data.orderId" - REQUIRED_FIELD_MISSING:
//	  {field: "payload.data.orderId", error_code: "REQUIRED_FIELD_MISSING",
//	   message: "Required field 'orderId' is missing"}
//
//	Field "payload.data.quantity" - INVALID_TYPE:
//	  {field: "payload.data.quantity", error_code: "INVALID_TYPE",
//	   message: "Expected integer, got string",
//	   details: {"expected": "integer", "actual": "string"}}
type ValidationError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// field: JSON path to the field that failed validation.
	// Uses dot notation: "payload.data.orderId", "payload.data.items[0].productId"
	// Root level: "payload.data"
	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// error_code: Standardized error code from ErrorCode enum.
	// Enables programmatic error handling across different schema types.
	ErrorCode string `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	// message: Human-readable error explanation.
	// Safe to show to end users or log for debugging.
	// Example: "Field 'orderId' must match pattern '^ORD-[0-9]+$', got 'invalid'"
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// details: Additional context about the error.
	// Contents depend on error_code:
	//
	//	INVALID_TYPE: {"expected": "integer", "actual": "string"}
	//	PATTERN_MISMATCH: {"pattern": "^[A-Z]+$", "value": "abc"}
	//	VALUE_OUT_OF_RANGE: {"min": "0", "max": "100", "value": "150"}
	Details       map[string]string `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationError) Reset() {
	*x = ValidationError{}
	mi := &file_proto_schema_v1_schema_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationError) ProtoMessage() {}

func (x *ValidationError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schema_v1_schema_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationError.ProtoReflect.Descriptor instead.
func (*ValidationError) Descriptor() ([]byte, []int) {
	return file_proto_schema_v1_schema_proto_rawDescGZIP(), []int{2}
}

func (x *ValidationError) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ValidationError) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ValidationError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidationError) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_proto_schema_v1_schema_proto protoreflect.FileDescriptor

const file_proto_schema_v1_schema_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/schema/v1/schema.proto\x12\x13nzovu.api.schema.v1\"\x91\x03\n" +
	"\x06Schema\x12\x1b\n" +
	"\tschema_id\x18\x01 \x01(\tR\bschemaId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12!\n" +
	"\fcontent_type\x18\x06 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\x12\x1b\n" +
	"\tis_active\x18\t \x01(\bR\bisActive\x12E\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2).nzovu.api.schema.v1.Schema.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcd\x01\n" +
	"\x10ValidationResult\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12<\n" +
	"\x06errors\x18\x02 \x03(\v2$.nzovu.api.schema.v1.ValidationErrorR\x06errors\x12!\n" +
	"\fvalidated_at\x18\x03 \x01(\x03R\vvalidatedAt\x12\x1b\n" +
	"\tschema_id\x18\x04 \x01(\tR\bschemaId\x12%\n" +
	"\x0eschema_version\x18\x05 \x01(\x05R\rschemaVersion\"\xe9\x01\n" +
	"\x0fValidationError\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12K\n" +
	"\adetails\x18\x04 \x03(\v21.nzovu.api.schema.v1.ValidationError.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xef\x02\n" +
	"\tErrorCode\x12\x11\n" +
	"\rUNKNOWN_ERROR\x10\x00\x12\x1a\n" +
	"\x16REQUIRED_FIELD_MISSING\x10\x01\x12\x10\n" +
	"\fINVALID_TYPE\x10\x02\x12\x12\n" +
	"\x0eINVALID_FORMAT\x10\x03\x12\x14\n" +
	"\x10PATTERN_MISMATCH\x10\x04\x12\x16\n" +
	"\x12VALUE_OUT_OF_RANGE\x10\x05\x12\x18\n" +
	"\x14ARRAY_LENGTH_INVALID\x10\x06\x12\x1d\n" +
	"\x19OBJECT_PROPERTIES_INVALID\x10\a\x12%\n" +
	"!ADDITIONAL_PROPERTIES_NOT_ALLOWED\x10\b\x12\x16\n" +
	"\x12ENUM_VALUE_INVALID\x10\t\x12\x14\n" +
	"\x10SCHEMA_NOT_FOUND\x10\n" +
	"\x12\x18\n" +
	"\x14CONTENT_TYPE_INVALID\x10\v\x12\x19\n" +
	"\x15PAYLOAD_SIZE_EXCEEDED\x10\f\x12\x1c\n" +
	"\x18SCHEMA_VALIDATION_FAILED\x10\rB0Z.github.com/adrien19/nzovu/api/schema/v1;schemab\x06proto3"

var (
	file_proto_schema_v1_schema_proto_rawDescOnce sync.Once
	file_proto_schema_v1_schema_proto_rawDescData []byte
)

func file_proto_schema_v1_schema_proto_rawDescGZIP() []byte {
	file_proto_schema_v1_schema_proto_rawDescOnce.Do(func() {
		file_proto_schema_v1_schema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_schema_v1_schema_proto_rawDesc), len(file_proto_schema_v1_schema_proto_rawDesc)))
	})
	return file_proto_schema_v1_schema_proto_rawDescData
}

var file_proto_schema_v1_schema_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_schema_v1_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_schema_v1_schema_proto_goTypes = []any{
	(ErrorCode)(0),           // 0: nzovu.api.schema.v1.ErrorCode
	(*Schema)(nil),           // 1: nzovu.api.schema.v1.Schema
	(*ValidationResult)(nil), // 2: nzovu.api.schema.v1.ValidationResult
	(*ValidationError)(nil),  // 3: nzovu.api.schema.v1.ValidationError
	nil,                      // 4: nzovu.api.schema.v1.Schema.MetadataEntry
	nil,                      // 5: nzovu.api.schema.v1.ValidationError.DetailsEntry
}
var file_proto_schema_v1_schema_proto_depIdxs = []int32{
	4, // 0: nzovu.api.schema.v1.Schema.metadata:type_name -> nzovu.api.schema.v1.Schema.MetadataEntry
	3, // 1: nzovu.api.schema.v1.ValidationResult.errors:type_name -> nzovu.api.schema.v1.ValidationError
	5, // 2: nzovu.api.schema.v1.ValidationError.details:type_name -> nzovu.api.schema.v1.ValidationError.DetailsEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_schema_v1_schema_proto_init() }
func file_proto_schema_v1_schema_proto_init() {
	if File_proto_schema_v1_schema_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_schema_v1_schema_proto_rawDesc), len(file_proto_schema_v1_schema_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_schema_v1_schema_proto_goTypes,
		DependencyIndexes: file_proto_schema_v1_schema_proto_depIdxs,
		EnumInfos:         file_proto_schema_v1_schema_proto_enumTypes,
		MessageInfos:      file_proto_schema_v1_schema_proto_msgTypes,
	}.Build()
	File_proto_schema_v1_schema_proto = out.File
	file_proto_schema_v1_schema_proto_goTypes = nil
	file_proto_schema_v1_schema_proto_depIdxs = nil
}
