// ChronoQueue Common API v1
//
// This file defines common data structures used across ChronoQueue APIs.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: proto/common/v1/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Payload represents the user data and metadata for a message.
//
// The Payload is the core data container in ChronoQueue that allows you to:
// - Store JSON-compatible structured data
// - Attach custom metadata for filtering, routing, or tracking
// - Enforce schema validation for data quality
//
// Example usage in Go:
//
//	payload := &common.Payload{
//	    Metadata: map[string]*structpb.Value{
//	        "source": structpb.NewStringValue("web-api"),
//	        "user_id": structpb.NewStringValue("user-123"),
//	        "correlation_id": structpb.NewStringValue("req-xyz"),
//	    },
//	    Data: dataStruct, // Your business data
//	    ContentType: "application/json",
//	    SchemaId: "order.v1",      // Optional: enforce schema
//	    SchemaVersion: 1,
//	}
//
// Best practices:
// - Use metadata for: correlation IDs, trace context, routing info, custom headers
// - Use content_type to identify the JSON representation
// - Use schema_id for validation in production to catch data quality issues early
// - Keep payloads under 256KB for optimal performance (configurable per queue)
type Payload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// metadata: Custom key-value pairs for message routing, filtering, and tracking.
	// Common uses: correlation IDs, trace context, source system, user ID, tenant ID.
	// These values are indexed and can be queried without deserializing the data field.
	Metadata map[string]*structpb.Value `protobuf:"bytes,1,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// data: The actual message payload as a JSON-compatible object.
	// This is your business data - orders, events, tasks, notifications, etc.
	// Values must be representable by google.protobuf.Struct.
	Data *structpb.Struct `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// content_type: MIME type identifying the JSON representation.
	// Supported values: "application/json" and "application/x-json".
	// An empty value defaults to "application/json".
	ContentType string `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// schema_id: Reference to a registered schema for validation.
	// If provided, ChronoQueue validates the data against this schema before accepting the message.
	// Example: "order.created.v1", "user.profile.v2"
	// Use RegisterSchema API to define schemas.
	SchemaId string `protobuf:"bytes,4,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	// schema_version: Version number of the schema to use.
	// Allows schema evolution while maintaining backward compatibility.
	// If omitted, uses the latest active version of schema_id.
	SchemaVersion int32 `protobuf:"varint,5,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload) Reset() {
	*x = Payload{}
	mi := &file_proto_common_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_proto_common_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *Payload) GetMetadata() map[string]*structpb.Value {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Payload) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Payload) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Payload) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *Payload) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

// LeasePolicy defines how long a single processing attempt is allowed to run,
// and how heartbeats can extend that time.
type LeasePolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// base_lease:
	// Initial lease duration for an attempt (L_base).
	// The attempt starts with this much time before timing out, unless extended.
	BaseLease *durationpb.Duration `protobuf:"bytes,1,opt,name=base_lease,json=baseLease,proto3" json:"base_lease,omitempty"`
	// max_extension:
	// Maximum additional time beyond base_lease that an attempt may obtain via
	// heartbeats (L_maxExt).
	//
	// Effective per-attempt cap:
	//
	//	base_lease + max_extension
	MaxExtension *durationpb.Duration `protobuf:"bytes,2,opt,name=max_extension,json=maxExtension,proto3" json:"max_extension,omitempty"`
	// heartbeat_timeout:
	// Maximum allowed gap between heartbeats (H).
	// If zero/unset, heartbeat-based timeout is disabled.
	HeartbeatTimeout *durationpb.Duration `protobuf:"bytes,3,opt,name=heartbeat_timeout,json=heartbeatTimeout,proto3" json:"heartbeat_timeout,omitempty"`
	// extend_step:
	// Amount of time to extend the lease when a renewal omits its duration or
	// when a heartbeat is received, until max_extension is exhausted.
	// If omitted at queue creation, defaults to one fifth of base_lease.
	//
	// Example:
	//
	//	base_lease = 3s
	//	max_extension = 10s
	//	extend_step = 2s
	//
	// The attempt can slide its lease by 2s increments up to ~13s total.
	ExtendStep *durationpb.Duration `protobuf:"bytes,4,opt,name=extend_step,json=extendStep,proto3" json:"extend_step,omitempty"`
	// max_renewals:
	// Maximum number of times a lease can be renewed/extended.
	// If set to 0 or unset, unlimited renewals are allowed.
	// This prevents messages from being held indefinitely by stuck workers.
	//
	// Example:
	//
	//	max_renewals = 5
	//	A worker can renew the lease up to 5 times, after which ExtendMessageLease fails.
	MaxRenewals   *int32 `protobuf:"varint,5,opt,name=max_renewals,json=maxRenewals,proto3,oneof" json:"max_renewals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeasePolicy) Reset() {
	*x = LeasePolicy{}
	mi := &file_proto_common_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeasePolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeasePolicy) ProtoMessage() {}

func (x *LeasePolicy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeasePolicy.ProtoReflect.Descriptor instead.
func (*LeasePolicy) Descriptor() ([]byte, []int) {
	return file_proto_common_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *LeasePolicy) GetBaseLease() *durationpb.Duration {
	if x != nil {
		return x.BaseLease
	}
	return nil
}

func (x *LeasePolicy) GetMaxExtension() *durationpb.Duration {
	if x != nil {
		return x.MaxExtension
	}
	return nil
}

func (x *LeasePolicy) GetHeartbeatTimeout() *durationpb.Duration {
	if x != nil {
		return x.HeartbeatTimeout
	}
	return nil
}

func (x *LeasePolicy) GetExtendStep() *durationpb.Duration {
	if x != nil {
		return x.ExtendStep
	}
	return nil
}

func (x *LeasePolicy) GetMaxRenewals() int32 {
	if x != nil && x.MaxRenewals != nil {
		return *x.MaxRenewals
	}
	return 0
}

var File_proto_common_v1_common_proto protoreflect.FileDescriptor

const file_proto_common_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/common/v1/common.proto\x12\x13nzovu.api.common.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1egoogle/protobuf/duration.proto\"\xba\x02\n" +
	"\aPayload\x12F\n" +
	"\bmetadata\x18\x01 \x03(\v2*.nzovu.api.common.v1.Payload.MetadataEntryR\bmetadata\x12+\n" +
	"\x04data\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04data\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x1b\n" +
	"\tschema_id\x18\x04 \x01(\tR\bschemaId\x12%\n" +
	"\x0eschema_version\x18\x05 \x01(\x05R\rschemaVersion\x1aS\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"\xc4\x02\n" +
	"\vLeasePolicy\x128\n" +
	"\n" +
	"base_lease\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\tbaseLease\x12>\n" +
	"\rmax_extension\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\fmaxExtension\x12F\n" +
	"\x11heartbeat_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x10heartbeatTimeout\x12:\n" +
	"\vextend_step\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\n" +
	"extendStep\x12&\n" +
	"\fmax_renewals\x18\x05 \x01(\x05H\x00R\vmaxRenewals\x88\x01\x01B\x0f\n" +
	"\r_max_renewalsB0Z.github.com/adrien19/nzovu/api/common/v1;commonb\x06proto3"

var (
	file_proto_common_v1_common_proto_rawDescOnce sync.Once
	file_proto_common_v1_common_proto_rawDescData []byte
)

func file_proto_common_v1_common_proto_rawDescGZIP() []byte {
	file_proto_common_v1_common_proto_rawDescOnce.Do(func() {
		file_proto_common_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_common_v1_common_proto_rawDesc), len(file_proto_common_v1_common_proto_rawDesc)))
	})
	return file_proto_common_v1_common_proto_rawDescData
}

var file_proto_common_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_common_v1_common_proto_goTypes = []any{
	(*Payload)(nil),             // 0: nzovu.api.common.v1.Payload
	(*LeasePolicy)(nil),         // 1: nzovu.api.common.v1.LeasePolicy
	nil,                         // 2: nzovu.api.common.v1.Payload.MetadataEntry
	(*structpb.Struct)(nil),     // 3: google.protobuf.Struct
	(*durationpb.Duration)(nil), // 4: google.protobuf.Duration
	(*structpb.Value)(nil),      // 5: google.protobuf.Value
}
var file_proto_common_v1_common_proto_depIdxs = []int32{
	2, // 0: nzovu.api.common.v1.Payload.metadata:type_name -> nzovu.api.common.v1.Payload.MetadataEntry
	3, // 1: nzovu.api.common.v1.Payload.data:type_name -> google.protobuf.Struct
	4, // 2: nzovu.api.common.v1.LeasePolicy.base_lease:type_name -> google.protobuf.Duration
	4, // 3: nzovu.api.common.v1.LeasePolicy.max_extension:type_name -> google.protobuf.Duration
	4, // 4: nzovu.api.common.v1.LeasePolicy.heartbeat_timeout:type_name -> google.protobuf.Duration
	4, // 5: nzovu.api.common.v1.LeasePolicy.extend_step:type_name -> google.protobuf.Duration
	5, // 6: nzovu.api.common.v1.Payload.MetadataEntry.value:type_name -> google.protobuf.Value
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_common_v1_common_proto_init() }
func file_proto_common_v1_common_proto_init() {
	if File_proto_common_v1_common_proto != nil {
		return
	}
	file_proto_common_v1_common_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_common_v1_common_proto_rawDesc), len(file_proto_common_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_common_v1_common_proto_goTypes,
		DependencyIndexes: file_proto_common_v1_common_proto_depIdxs,
		MessageInfos:      file_proto_common_v1_common_proto_msgTypes,
	}.Build()
	File_proto_common_v1_common_proto = out.File
	file_proto_common_v1_common_proto_goTypes = nil
	file_proto_common_v1_common_proto_depIdxs = nil
}
